### ISSUE TITLE
Taiko fails while trying to click "Google Search"

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#11]
To reproduce this

```
> openBrowser()
 ✔ Browser and page initialized
> goto("http://google.com")
 ✔ Navigated to url "https://www.google.co.in/?gfe_rd=cr&dcr=0&ei=ikIAWpWdMoby8Aeyu5uACw&gws_rd=ssl"
> click("Google Search")
 ✘ Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined, run `.trace` for more info.
> 

```

**Comment by kashishm** [comment]
The `Google Search` is an input field. The following script works
```
> openBrowser()
 ✔ Browser and page initialized
> goto("http://google.com")
 ✔ Navigated to url "https://www.google.co.in/?gfe_rd=cr&dcr=0&ei=5X0BWsnyGO6cX6rDmfgK&gws_rd=ssl"
> write("hello", into(inputField('title', 'Search')))
 ✔ Wrote hello into the input field with "title = Search"
> click(inputField('value', 'Google Search'), false)
 ✔ Clicked input field with "value = Google Search"
```

**Comment by zabil** [comment]
The user can't make that out unless they inspect the DOM.

`write` without a parameter can write to the currently focused element.

Is there a way for click to handle input fields also?

**Comment by kashishm** [comment]
@zabil How about this?
```
> openBrowser()
 ✔ Browser and page initialized
> goto("http://google.com")
 ✔ Navigated to url "https://www.google.co.in/?gfe_rd=cr&dcr=0&ei=H4UBWsmINPCcX_P3lagK&gws_rd=ssl"
> write("hello")
 ✔ Wrote hello into the focussed element.
> click(inputField('Google Search'))
 ✔ Clicked input field with "value = Google Search"
```

**Comment by zabil** [comment]
`focussed` -> `focused`
 `> write("hello")`  :+1: 

`click(inputField('Google Search'))` -> `click('Google Search')`
There is way the user will know it's an input field.
Google search is the simplest test case a user will attempt. So zero friction here.

**Comment by kashishm** [comment]
@zabil Fixed it.
```
> openBrowser()
 ✔ Browser and page initialized
> goto("http://google.com")
 ✔ Navigated to url "https://www.google.co.in/?gfe_rd=cr&dcr=0&ei=gJQBWtziIOKcX4qQs_gK&gws_rd=ssl"
> write("hello")
 ✔ Wrote hello into the focused element.
> click('Google Search')
 ✔ Clicked element containing text "Google Search"
> closeBrowser()
 ✔ Browser and page closed
```

**Comment by sguptatw** [comment]
**Expected behavior**
Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined

**Actual behavior**
```
      Error Message: Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined
      Stacktrace:
      Error: Protocol error (DOM.getBoxModel): Could not compute box model. undefined
          at Session._onMessage (C:\work\testFolder\taiko\js_puppeteer\node_modules\puppeteer\lib\Connection.js:194:25

          at Connection._onMessage (C:\work\testFolder\taiko\js_puppeteer\node_modules\puppeteer\lib\Connection.js:98:
)
          at emitOne (events.js:115:13)
          at WebSocket.emit (events.js:210:7)
          at Receiver._receiver.onmessage (C:\work\testFolder\taiko\js_puppeteer\node_modules\ws\lib\WebSocket.js:143:
)
          at Receiver.dataMessage (C:\work\testFolder\taiko\js_puppeteer\node_modules\ws\lib\Receiver.js:389:14)
          at Receiver.getData (C:\work\testFolder\taiko\js_puppeteer\node_modules\ws\lib\Receiver.js:330:12)
          at Receiver.startLoop (C:\work\testFolder\taiko\js_puppeteer\node_modules\ws\lib\Receiver.js:165:16)
          at Receiver.add (C:\work\testFolder\taiko\js_puppeteer\node_modules\ws\lib\Receiver.js:139:10)
          at Socket._ultron.on (C:\work\testFolder\taiko\js_puppeteer\node_modules\ws\lib\WebSocket.js:139:22)
```

**Steps to replicate**
* Run [project](https://github.com/getgauge-examples/js_puppeteer) with openBrowser({headless:false})
* run it a couple of times and we start getting the error `Could not compute box model. undefined`

**Comment by kashishm** [comment]
@sguptatw I tried it for 20 times still cannot replicate this issue.
