### ISSUE TITLE
Unable to require module 'taiko'

### ISSUE THREAD

**Issue by ksail** [getgauge/taiko#1105]
27-02-2020 12:29:03.458 [js] [ERROR] Unable to require module 'taiko' in C:\workspace\ui\e2etests\tests\step_implementation.js
Error: Cannot find module 'taiko'
Require stack:
- C:\workspace\ui\e2etests\tests\step_implementation.js
- 
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:793:17)
    at Function.Module._load (internal/modules/cjs/loader.js:686:27)
    at Module.require (internal/modules/cjs/loader.js:848:19)
    at C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\req-manager.js:36:18
    at Req.load (C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\req-manager.js:50:5)
    at fn (C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\req-manager.js:61:20)
    at C:\workspace\ui\e2etests\tests\step_implementation.js:4:103
    at Script.runInContext (vm.js:127:20)
    at Object.runInContext (vm.js:290:6)
    at VM.run (C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\vm.js:59:8)
27-02-2020 12:29:03.465 [Gauge] [INFO] ## Search Taiko Repository
27-02-2020 12:29:03.468 [js] [ERROR] Error executing tests\step_implementation.js
C:\workspace\ui\e2etests\tests\step_implementation.js:4
const { openBrowser,write, closeBrowser, goto, press, screenshot, text, focus, textBox, toRightOf } = require('taiko');
        ^

TypeError: Cannot destructure property `openBrowser` of 'undefined' or 'null'.
    at C:\workspace\ui\e2etests\tests\step_implementation.js:4:7
    at Script.runInContext (vm.js:127:20)
    at Object.runInContext (vm.js:290:6)
    at VM.run (C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\vm.js:59:8)
    at VM.runFile (C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\vm.js:73:8)
    at C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\impl-loader.js:13:10
    at Array.forEach (<anonymous>)
    at C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\impl-loader.js:10:31
    at new Promise (<anonymous>)
    at Object.loadImpl [as load] (C:\Users\SY\AppData\Roaming\gauge\plugins\js\2.3.8\src\impl-loader.js:6:10)

### Expected behavior
Taiko module imported

### Actual behavior
Unable to find module taiko

### Steps to reproduce
1. npm install taiko into the project - install using -g
2. Check taiko version
3. Verify taiko is in node_modules for project - it is in node_modules

### Versions
```
Paste `node` and `taiko` versions here.
```taiko -v
Version: 1.0.4 (Chromium: 81.0.3994.0) RELEASE

gauge -v
Gauge version: 1.0.7
Commit Hash: ed7b4fd6

Plugins
-------
html-report (4.0.9)
js (2.3.8)
screenshot (0.0.1)

node -v
v12.14.1

**Comment by zabil** [comment]
What command are you running?

This looks like a gauge project.
Please run cd to e2etests folder and run 

```
npm run test
```

**Comment by zabil** [comment]
This is being discussed at

https://spectrum.chat/taiko/general/help-taiko-unable-to-find-module-error-even-when-taiko-is-in-nodemodules~26ffd424-f55c-4a94-9efa-a47f0821f526
