### ISSUE TITLE
Hangs in REPL mode

### ISSUE THREAD

**Issue by BugDiver** [getgauge/taiko#116]
Sometime taiko hangs in REPL mode, after issuing `openBrowser` command and does not allow to do anything. After pressing `Enter` or `Ctrl + C` the control comes back but none of the commands work after that.
Running in headful mod gives the following error

```
Error: unexpected server response (500)
   at ClientRequest._req.on (/usr/local/lib/node_modules/taiko/node_modules/ws/lib/WebSocket.js:653:21)
   at emitOne (events.js:116:13)
   at ClientRequest.emit (events.js:211:7)
   at HTTPParser.parserOnIncomingClient (_http_client.js:543:21)
   at HTTPParser.parserOnHeadersComplete (_http_common.js:112:17)
   at Socket.socketOnData (_http_client.js:440:20)
   at emitOne (events.js:116:13)
   at Socket.emit (events.js:211:7)
   at addChunk (_stream_readable.js:263:12)
   at readableAddChunk (_stream_readable.js:250:11)
```

### Versions
```
Node - 8.11.4 LTS
Taiko - 0.1.0
```

**Comment by BugDiver** [comment]
After some debugging found out that if CRI is not able to connect to `chrome` it tries to connect again and again which cause the REPL to hung.
Ref - https://github.com/getgauge/taiko/blob/ddd7db3a57be5b6e9a1922d85928050077f583ed/lib/taiko.js#L42

The stacktrace -
```
{ Error: connect ECONNREFUSED ::1:9222
   at Object._errnoException (util.js:992:11)
   at _exceptionWithHostPort (util.js:1014:20)
   at TCPConnectWrap.afterConnect [as oncomplete] (net.js:1186:14)
 code: 'ECONNREFUSED',
 errno: 'ECONNREFUSED',
 syscall: 'connect',
 address: '::1',
 port: 9222 }
```

**Comment by Apoorva-GA** [comment]
Fix should be available in 271f059

**Comment by Apoorva-GA** [comment]
Steps to replicate : 

1. Don't map localhost to ip `127.0.0.1`
2. Try running taiko from REPL.

**Comment by sguptatw** [comment]
Working as expected with commit - a5da76d97ef5a1e6ca17534424747b96003c8b13
