### ISSUE TITLE
closeBrowser() sometimes fails 

### ISSUE THREAD

**Issue by usualstuff** [getgauge/taiko#1241]
### Expected behavior
Browser closes.

### Actual behavior
Taiko trows an error:
```
Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (/opt/integration-tests/node_modules/ws/lib/websocket.js:729:17)
    at WebSocket.send (/opt/integration-tests/node_modules/ws/lib/websocket.js:339:7)
    at Chrome._enqueueCommand (/opt/integration-tests/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
    at /opt/integration-tests/node_modules/chrome-remote-interface/lib/chrome.js:87:22
    at new Promise (<anonymous>)
    at Chrome.send (/opt/integration-tests/node_modules/chrome-remote-interface/lib/chrome.js:86:20)
    at handler (/opt/integration-tests/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at /opt/integration-tests/node_modules/taiko/lib/taiko.js:116:33
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (/opt/integration-tests/node_modules/taiko/lib/taiko.js:113:24)
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
    at validate (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3466:11)
    at Object.module.exports.closeBrowser (/opt/integration-tests/node_modules/taiko/lib/taiko.js:387:3)
    at Object.module.exports.<computed> [as closeBrowser] (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3596:36)
    at process.exitOnUnhandledFailures (/opt/integration-tests/node_modules/taiko/bin/taiko.js:27:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
...
(previous error repeats until OOM)
```

### Steps to reproduce
Launch tests repeatetly until it fails. Sometimes it take 20 tries, sometimes 1.

### Versions
```
Taiko: Version: 1.0.9 (Chromium: 83.0.4103.0) RELEASE
Node: v13.14.0
```

Note: we're running taiko inside docker container.

After some debugging I discovered that actual error happens when taiko calls `page.close()` from [here](https://github.com/getgauge/taiko/blob/v1.0.9/lib/taiko.js#L402). 

Taiko send to browser something like this (logged [here](https://github.com/websockets/ws/blob/master/lib/websocket.js#L326)):
```
DATA
{"id":13,"method":"Page.close","params":{}}
OPTIONS
[Function (anonymous)]
CB
undefined

DATA
{"id":14,"method":"DOM.getDocument","params":{}}
OPTIONS
[Function (anonymous)]
CB
undefined
```

I don't know why `DOM.getDocument` is called but it's failing because browser is closing at the time.

Tests file:
```
  const { openBrowser, goto, write, near, textBox, into, click, screenshot, screencast, closeBrowser } = require('taiko');
  (async () => {
      try {
        await openBrowser({args: [
            '--disable-gpu',
            '--disable-dev-shm-usage',
            '--disable-setuid-sandbox',
            '--no-first-run',
            '--no-sandbox',
            '--no-zygote']})
          await goto("http://localhost:8080");
          await write("user");
          await write("password", into(textBox(near("Password"))));
          await press("Enter");
          await click("Sign out");
      } catch (error) {
          console.error(error);
      } finally {
          await closeBrowser();
      }
  })();    
```

**Comment by NivedhaSenthil** [comment]
From the log the error seems to be happening when trying to closeBrowser but the connection is already closing... doesn't seem to be happening when `page.close()` as `validate` is called even before that. Did the browser crash when this error occurred  ?

**Comment by usualstuff** [comment]
@NivedhaSenthil If I understanding everything correctly it happens in this order:
1) `closeBrowser()` is called
2) `page.close()` is called
3) browser begins to close
4) something calls `DOM.getDocument` (`taiko/lib/taiko.js:113:24`) and failing with an error
5) `closeBrowser()` is being called again and failing on `validate` because browser is closing
6) step 5 then repeats indefinitely

I don't think that browser is crashing because it only happens on `closeBrowser()`.

The error log usually very long and looks like this:
```
Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (/opt/integration-tests/node_modules/ws/lib/websocket.js:729:17)
    at WebSocket.send (/opt/integration-tests/node_modules/ws/lib/websocket.js:339:7)
    at Chrome._enqueueCommand (/opt/integration-tests/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
    at /opt/integration-tests/node_modules/chrome-remote-interface/lib/chrome.js:87:22
    at new Promise (<anonymous>)
    at Chrome.send (/opt/integration-tests/node_modules/chrome-remote-interface/lib/chrome.js:86:20)
    at handler (/opt/integration-tests/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at /opt/integration-tests/node_modules/taiko/lib/taiko.js:116:33
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (/opt/integration-tests/node_modules/taiko/lib/taiko.js:113:24)
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
    at validate (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3466:11)
    at Object.module.exports.closeBrowser (/opt/integration-tests/node_modules/taiko/lib/taiko.js:387:3)
    at Object.module.exports.<computed> [as closeBrowser] (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3596:36)
    at process.exitOnUnhandledFailures (/opt/integration-tests/node_modules/taiko/bin/taiko.js:27:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
    at validate (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3466:11)
    at Object.module.exports.closeBrowser (/opt/integration-tests/node_modules/taiko/lib/taiko.js:387:3)
    at Object.module.exports.<computed> [as closeBrowser] (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3596:36)
    at process.exitOnUnhandledFailures (/opt/integration-tests/node_modules/taiko/bin/taiko.js:27:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
    at validate (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3466:11)
    at Object.module.exports.closeBrowser (/opt/integration-tests/node_modules/taiko/lib/taiko.js:387:3)
    at Object.module.exports.<computed> [as closeBrowser] (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3596:36)
    at process.exitOnUnhandledFailures (/opt/integration-tests/node_modules/taiko/bin/taiko.js:27:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
    at validate (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3466:11)
    at Object.module.exports.closeBrowser (/opt/integration-tests/node_modules/taiko/lib/taiko.js:387:3)
    at Object.module.exports.<computed> [as closeBrowser] (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3596:36)
    at process.exitOnUnhandledFailures (/opt/integration-tests/node_modules/taiko/bin/taiko.js:27:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
    at validate (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3466:11)
    at Object.module.exports.closeBrowser (/opt/integration-tests/node_modules/taiko/lib/taiko.js:387:3)
    at Object.module.exports.<computed> [as closeBrowser] (/opt/integration-tests/node_modules/taiko/lib/taiko.js:3596:36)
    at process.exitOnUnhandledFailures (/opt/integration-tests/node_modules/taiko/bin/taiko.js:27:19)
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```

**Comment by NivedhaSenthil** [comment]
Hey yes that is going into an infinite loop because of closeBrowser in runner. Thanks for the investigation, we will try and fix this soon.

**Comment by usualstuff** [comment]
@NivedhaSenthil thank you! Feel free to ask for any help with this.
