### ISSUE TITLE
Getting MaxListenersExceededWarning: Possible EventEmitter memory leak detected.

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#126]
**Expected behavior**
Should execute taiko scripts seamlessly.

**Actual behavior**
Getting
```
(node:30642) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. <event> listeners added. Use emitter.setMaxListeners() to increase limit
```

**Steps to replicate**
* Run the js-taiko tests https://github.com/getgauge-examples/js-taiko
> Getting the error on CI https://build.gauge.org/go/tab/build/detail/Taiko/174/specs/1/specs

**Version**
commit - a5da76d97ef5a1e6ca17534424747b96003c8b13

Related to https://github.com/getgauge/taiko/issues/123

**Comment by NivedhaSenthil** [comment]
Fix should be available in ee53aed.

**Comment by sguptatw** [comment]
Still getting the exception
`(node:30642) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. <event> listeners added. Use emitter.setMaxListeners() to increase limit`

**Steps to replicate**
* Run the following script
```
(async () => {
    try {
        await openBrowser({headless:false});
        await goto("thetrainline.com",{timeout:20000});
 
        await write("London",into(inputField(toRightOf("From"))));
        await press("Enter");
        await write("Manchester");
        await press("Enter");
        await click("Tomorrow")
        await click(button({"type":"submit"}));
        await click(radioButton(toRightOf("Cheapest First Class Single")))
//        await click(radioButton(toRightOf("First Class Single")))
//        await highlight("Continue");
        await click("Continue");
        await screenshot();

        await click(checkBox(toLeftOf("Table Seat")));
        await click("Continue");
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
 })();
```

**Comment by NivedhaSenthil** [comment]
Fix should be available in [commit](https://github.com/getgauge/taiko/commit/2739f363ce842c7ec2d5ba8de36a9723843d7905)

**Comment by sguptatw** [comment]
For the following script getting the memory leak error
```
const { openBrowser, goto, inputField, into, write, press, button, click, link, below, radioButton, contains, toLeftOf, checkBox } = require('taiko');

(async () => {
   try {
       await openBrowser({headless:false});
       await goto("https://www.greateranglia.co.uk/",{timeout:"25000"});
       await write("London",into(inputField({"placeHolder":"Enter origin station"})));
       await press("Enter");
       await write("Manchester",into(inputField({"placeHolder":"Enter destination station"})));
       await press("Enter");
       await click(button("Find times and tickets"));
       await click(radioButton(below(link("Later"))));
       await click("Next");
       await click("Continue");
       await write("email@gmail.com",into(inputField({"placeHolder":"Your email address"})));
       await click(radioButton(toLeftOf(contains("I don't have a password"))));
       await click("Continue");
       await click("Continue");
       await click("Proceed to payment");
       await click(radioButton({"id":"PaymentMethod_OnAccount_Option"}));
       await click("Buy Tickets");
       await click(radioButton(toLeftOf("No thank you")));
       await click("Buy Tickets");
       await click(checkBox(toLeftOf(contains("I've read"))));
       await click("Buy Tickets");
   } catch (e) {
       console.error(e);
   } finally {
       closeBrowser();
   }
})();
```
![MemoryLeak.png](https://waffleio-direct-uploads-production.s3.amazonaws.com/uploads/571dd284c8c2e113000ddd5a/125516c66e82c728ace21e0d46c591972c909a858ae8b401e81fe086264c22703d46f96925d3b62ce7137d04095c1df915585b42fcf98d7aa5e53972984019af80330b2b9b645bf9fa9015ad03bb2a8a4a86b0bf8b4cc6e03c26ef8a9d02.png)

commit - 6e21ca751ea8ed12ddd0679ba92343aa5d9362a6

**Comment by NivedhaSenthil** [comment]
Fix should be available in fa5d11c . Removing all listeners after waiting so that if there is no event happened none will wait hanging. hopefully should solve all cases

**Comment by carpeliam** [comment]
I ran into this today with node v14.2.0 and Chromium 724157 on a Mac:

```
(node:98235) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added to [ChildProcess]. Use emitter.setMaxListeners() to increase limit
    at _addListener (events.js:390:17)
    at ChildProcess.addListener (events.js:406:10)
    at ChildProcess.once (events.js:437:8)
    at /Users/liam/workspace/funproj/node_modules/taiko/lib/taiko.js:349:19
    at new Promise (<anonymous>)
    at _closeBrowser (/Users/liam/workspace/funproj/node_modules/taiko/lib/taiko.js:348:32)
    at Object.<anonymous>.module.exports.closeBrowser (/Users/liam/workspace/funproj/node_modules/taiko/lib/taiko.js:330:9)
    at Object.<anonymous>.module.exports.<computed> (/Users/liam/workspace/funproj/node_modules/taiko/lib/taiko.js:3225:36)
    at _callee26$ (/Users/liam/workspace/funproj/__tests__/task-master-test.js:138:15)
    at tryCatch (/Users/liam/workspace/funproj/node_modules/regenerator-runtime/runtime.js:45:40)
  ●  process.exit called with "1"
```

This happens when I call `closeBrowser` in an `afterEach` block; the browser closes, but the promise never resolves.

**Comment by NivedhaSenthil** [comment]
Is `closeBrowser` awaited properly ? since the exit listener is added once they should get removed once closeBrowser is done successfully ...If you are facing the issue please provide an repro. Also try with the latest version of Taiko
