### ISSUE TITLE
Highlight function failing even though in REPL mode the function works

### ISSUE THREAD

**Issue by amitsarkar007** [getgauge/taiko#1281]
### Expected behavior
Highlight function should work

### Actual behavior
Highlight function doesn't work while execution of this code

```
const { openBrowser, goto, tap, goBack, clearHighlights, tableCell, press, scrollDown, screenshot, click, below, closeBrowser, text, textBox, highlight, radioButton, checkBox, toRightOf } = require('taiko');
(async () => {
    try {
        await openBrowser({ headless: false });
        await goto('https://ultimateqa.com/simple-html-elements-for-automation/');
        await click("Click Me!");
        await goBack();
        await click("Click Me");
        await goBack();
        await scrollDown(500);
        await click($(`.et_pb_image_wrap`));
        await goBack();
        await write("arun",into(textBox('Name')));
        await write("arun@gmail.com",into(textBox('Email')));
        await clear(textBox('Email'));
        await clear(textBox('Name'));
        await click(radioButton('Male'));
        await click(radioButton('Female'));
        await click(radioButton('Other'));
        await click(checkBox('I have a bike'));
        await click(checkBox('I have a car'));
        await click(checkBox('I have a bike'));
        await click(checkBox('I have a car'));
        await scrollDown(500);
        await click($(`//select`));
        await press(['ArrowDown', 'ArrowDown', 'Enter']);
        await click("Tab 1");
        await click("Tab 2");
        await tap("Tab 2 content");
        await click("Open toggle to read text");
        await scrollDown(500);
        await highlight(tableCell({row:1, col:2}));
        await clearHighlights();
        await scrollDown(500);
        await click("Go to login page");
        await goBack();
        await click('Xpath Button 1');
        await goBack();
        await click('Xpath Button 1',below('Button 2'));
        await goBack();
        await scrollDown(500);
        await highlight("Highlight me"); //CODE FAILS TO EXECUTE
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
**Code Execution Error**
```
taiko "C:\Users\Neo\OneDrive\GAUGE + TAIKO\Taiko-UltimateQA.js"
[PASS] Browser opened
[PASS] Navigated to URL https://ultimateqa.com/simple-html-elements-for-automation/
[PASS] Clicked element matching text "Click Me!" 1 times
[PASS] Performed clicking on browser back button
[PASS] Clicked element matching text "Click Me" 1 times
[PASS] Performed clicking on browser back button
[PASS] Clicked custom selector $(.et_pb_image_wrap) 1 times
[PASS] Performed clicking on browser back button
[PASS] Wrote arun into the text field with label Name 
[PASS] Wrote arun@gmail.com into the text field with label Email 
[PASS] Cleared text field with label Email 
[PASS] Cleared text field with label Name 
[PASS] Clicked radio button with label Male  1 times
[PASS] Clicked radio button with label Female  1 times
[PASS] Clicked radio button with label Other  1 times
[PASS] Clicked checkbox with label I have a bike  1 times
[PASS] Clicked checkbox with label I have a car  1 times
[PASS] Clicked checkbox with label I have a bike  1 times
[PASS] Clicked checkbox with label I have a car  1 times
[PASS] Clicked custom selector $(//select) 1 times
[PASS] Pressed the ArrowDown + ArrowDown + Enter key
[PASS] Clicked element matching text "Tab 1" 1 times
[PASS] Clicked element matching text "Tab 2" 1 times
[PASS] Tap has been performed
[PASS] Clicked element matching text "Open toggle to read text" 1 times
[PASS] Highlighted the tableCell at row:1 and column:2
[PASS] Cleared all highlights for this page.
[PASS] Clicked element matching text "Go to login page" 1 times
[PASS] Performed clicking on browser back button
[PASS] Clicked element matching text "Xpath Button 1" 1 times
[PASS] Performed clicking on browser back button
[PASS] Clicked element matching text "Xpath Button 1" 1 times
[PASS] Performed clicking on browser back button
ProtocolError: No node with given id found
    at C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\node_modules\chrome-remote-interface\lib\chrome.js:93:35
    at Chrome._handleMessage (C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\node_modules\chrome-remote-interface\lib\chrome.js:256:17)
    at WebSocket.<anonymous> (C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\node_modules\chrome-remote-interface\lib\chrome.js:234:22)
    at WebSocket.emit (events.js:310:20)
    at Receiver.receiverOnMessage (C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\node_modules\ws\lib\websocket.js:800:20)
    at Receiver.emit (events.js:310:20)
    at Receiver.dataMessage (C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\node_modules\ws\lib\receiver.js:436:14)    
    at C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\node_modules\ws\lib\receiver.js:393:23
    at C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\node_modules\ws\lib\permessage-deflate.js:306:9
    at C:\Users\Neo\AppData\Roaming\npm\node_modules\taiko\node_modules\ws\lib\permessage-deflate.js:385:7 {
  request: { method: 'DOM.resolveNode', params: { nodeId: 1855 } },
  response: { code: -32000, message: 'No node with given id found' }
}
[PASS] Browser closed
```

In **REPL** mode the code passes

```
> highlight("Highlight me")
[PASS] Highlighted the element matching text "Highlight me"
```

### Versions
```
taiko --version
Version: 1.0.11 (Chromium: 84.0.4143.0) RELEASE

node --version
v12.16.3

```

**Comment by NivedhaSenthil** [comment]
This is happening because the elements slide after the clicking coordinates is calculated and hence click does not trigger a page navigation. As a result `goBack` navigates to blank page and fails to find element in subsequent actions.

Closing this issue as it is related to the performance issue of the site being tested and taiko can not do much about it.
