### ISSUE TITLE
Browser connection is missing when trying to close tab using closeTab()

### ISSUE THREAD

**Issue by windyliu1118** [getgauge/taiko#1285]
I execute one test case, but it will always failed when close current tab.
Then error info is as below:
```
[DEPRECATED] gauge.screenshotFn will be removed soon, use gauge.customScreenshotWriter instead.
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
at validate (/Users/windyliu/Workstream/workstream-auto/node_modules/taiko/lib/taiko.js:3455:11)
at module.exports.screenshot (/Users/windyliu/Workstream/workstream-auto/node_modules/taiko/lib/taiko.js:2134:3)
at module.exports.(anonymous function) (/Users/windyliu/Workstream/workstream-auto/node_modules/taiko/lib/taiko.js:3585:36)
at Object.gauge.screenshotFn (/Users/windyliu/Workstream/workstream-auto/tests/step_helper.js:131:18)
at Promise (/Users/windyliu/.gauge/plugins/js/2.3.10/src/screenshot.js:44:34)
at new Promise (<anonymous>)
at /Users/windyliu/.gauge/plugins/js/2.3.10/src/screenshot.js:42:14
at Object.capture (/Users/windyliu/.gauge/plugins/js/2.3.10/src/screenshot.js:73:10)
at /Users/windyliu/.gauge/plugins/js/2.3.10/src/executor.js:70:22
at process._tickCallback (internal/process/next_tick.js:68:7)
        Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50495: connect: connection refused"
        Stacktrace: 
        Failed Step: Answer quiz question with attempt as "fail"
        Specification: specs/01_positions.spec:164
        Error Message: rpc error: code = Unavailable desc = transport is closing
        Stacktrace: 
    Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50495: connect: connection refused"
    Stacktrace: 
  Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50495: connect: connection refused"
  Stacktrace: 
  Error Message: rpc error: code = Unavailable desc = all SubConns are in TransientFailure, latest connection error: connection error: desc = "transport: Error while dialing dial tcp 127.0.0.1:50495: connect: connection refused"
  Stacktrace:
```
My env is as below:
```
node: 10.16.3
Taiko: Version: 1.0.9 RELEASE
Gauge version: 1.0.7
Commit Hash: ed7b4fd6
Plugins
-------
html-report (4.0.9)
js (2.3.7)
screenshot (0.0.1)
xml-report (0.2.3)
```

code is as below:
```
step("Answer quiz question with attempt as <status>", async(status) => {
    let quiz_url = await getApplicantURL("take a short online quiz");
    await closeApplicantPanel();
    await waitFor(2000);
    await openTab(quiz_url);
    // answer quiz question
    await waitFor(async() => await button("Send").exists());
    let radio_buttons = await $(".question-mcq-control").elements();
    console.log(await radio_buttons[1].text());
    await click(radio_buttons[1]);
    await click(radio_buttons[4]);
    await click(button("Send"));
    await waitFor(async() => await text("Unfortunately you didn't answer enough questions correctly to move forward, but don't worry, you have 1 more attempts remaining.").exists());
    await click("Try again");
    let radio_buttons2 = await $(".question-mcq-control").elements();
    if (status == "fail") {
        await click(radio_buttons2[0]);
        await click(radio_buttons2[5]);
        await click(button("Send"));
        await waitFor(async() => await text("Thank you for your response!").exists());
    } else {
        await click(radio_buttons2[0]);
        await click(radio_buttons2[3]);
        await click(button("Send"));
        await waitFor(async() => button("Next step").exists());
    }
    await closeTab();
    await closeTab();
    await reload(currentURL());
});
```
I have 4 statement closeTab() in my test case, the 1st 2 of them works fine and the tab is closed as expected. But when trying to close the current Tab in the 3rd statement, the browser connection closed. It weird.
for the API closeTab() , is there some kind of limit count to use?

in my case, I have more than 3 tabs opened, and I closed 1 tab, and then the error occurs and the browser connection is missing, and then the test failed. And actually the browser is not closed, only the browser connection with taiko is missing.
I think there is something wrong with the API closeTab()

**Comment by amitsarkar007** [comment]
I was having a similar issue while executing one of my codes. But then handled it as follows

```
//Open and close a new Tab
await goto("https://the-internet.herokuapp.com/windows");
await click("Click Here");
await closeTab();
        
//Highlight different Shadow DOM
await goto("https://the-internet.herokuapp.com/shadowdom");
await highlight(`Let's`);
await highlight(listItem(`Let's`));
```
So from opening a tab, closing it and then navigating to another URL, this worked. 

But I did get the error initially during execution. It seems Taiko doesn't know which window to focus. This code sequence gave the error you got

```
> goto("https://the-internet.herokuapp.com/windows");
[PASS] Navigated to URL https://the-internet.herokuapp.com/windows
>  value: {
  url: 'https://the-internet.herokuapp.com/windows',
  status: { code: 200, text: 'OK' }
}
[PASS] Navigated to URL https://the-internet.herokuapp.com/windows
> click("Click Here")
[PASS] Clicked element matching text "Click Here" 1 times
> switchTo("The Internet")
[PASS] Switched to tab matching The Internet
> closeTab("New Window")
[PASS] Closed tab(s) matching New Window
> goto("https://the-internet.herokuapp.com");
"[FAIL] Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes., run 
`.trace` for more info."
```

**Comment by NivedhaSenthil** [comment]
Thanks for the sample to replicate @amitsarkar007 I could see the error too
