### ISSUE TITLE
Error: WebSocket is not open: readyState 2 (CLOSING)

### ISSUE THREAD

**Issue by ceisele-r** [getgauge/taiko#1304]
### Expected behavior
Tests execute successfully

### Actual behavior
The following error occurs very often during/after (unsure) test runs when executed in a Github Action:
```
Error: WebSocket is not open: readyState 2 (CLOSING)
    at sendAfterClose (/github/workspace/app/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:729:17)
    at WebSocket.send (/github/workspace/app/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:339:7)
    at Chrome._enqueueCommand (/github/workspace/app/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
    at /github/workspace/app/node_modules/chrome-remote-interface/lib/chrome.js:87:22
    at new Promise (<anonymous>)
    at Chrome.send (/github/workspace/app/node_modules/chrome-remote-interface/lib/chrome.js:86:20)
    at handler (/github/workspace/app/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at /github/workspace/app/node_modules/taiko/lib/taiko.js:120:33
    at new Promise (<anonymous>)
    at Proxy.<anonymous> (/github/workspace/app/node_modules/taiko/lib/taiko.js:117:24)
    at EventEmitter.<anonymous> (/github/workspace/app/node_modules/taiko/lib/handlers/pageHandler.js:41:8)
```

### Steps to reproduce
I have no idea what is causing this as it is logged below a test that is skipped via `it.skip` and that's the only test in this `describe` block.

`before` and `after` in this `describe` look like this:
```
before(async () => {
      ...

      await openBrowser({
        args: [
          "--disable-gpu",
          "--disable-dev-shm-usage",
          "--disable-setuid-sandbox",
          "--no-first-run",
          "--no-sandbox",
          "--no-zygote"
        ]
      });
    });

    after(async () => {
      await closeBrowser();
    });
```

### Versions
```
node v12.16.2
taiko 1.0.11
```

**Comment by NivedhaSenthil** [comment]
This exception seems to be happening because of some listeners that are trying to run while the connection is closing, taiko might have to remove them properly before performing closing connection. Thanks for reporting we will take a look.

**Comment by markvillar** [comment]
I am also getting the same result ocassionally, and it seems to happen at every other run of the test.

All tests were passing with or without the error occuring.

I believe the error occurs somewhere in between the last step and the teardown step, as it does not even get the chance to run the tear down step that I have setup.

```
Error: WebSocket is not open: readyState 2 (CLOSING)
at sendAfterClose (/workspace/test/gauge/node_modules/ws/lib/websocket.js:726:17)
at WebSocket.send (/workspace/test/gauge/node_modules/ws/lib/websocket.js:336:7)
at Chrome._enqueueCommand (/workspace/test/gauge/node_modules/chrome-remote-interface/lib/chrome.js:281:18)
at /workspace/test/gauge/node_modules/chrome-remote-interface/lib/chrome.js:87:22
at new Promise (<anonymous>)
at Chrome.send (/workspace/test/gauge/node_modules/chrome-remote-interface/lib/chrome.js:86:20)
at handler (/workspace/test/gauge/node_modules/chrome-remote-interface/lib/api.js:32:23)
at /workspace/test/gauge/node_modules/taiko/lib/taiko.js:112:33
at new Promise (<anonymous>)
at Proxy.<anonymous> (/workspace/test/gauge/node_modules/taiko/lib/taiko.js:105:24)
[Gauge] [CRITICAL] js runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing
```

It is quite flaky, other times it works perfectly, and I don't get these errors.

```
Environment

Node: v14.11.0
Taiko: 1.0.23 (Chromium: 86.0.4240.0) RELEASE

Gauge: 1.1.4
Plugins
-------
html-report (4.0.12)
js (2.3.12)
screenshot (0.0.1)
```

**Comment by zabil** [comment]
@markvillar can you give more info about the hardware/os etc these tests run on?

**Comment by markvillar** [comment]
@zabil I am running it on MacBook Pro (2015) running macOS 10.15.7


I also have log from CircleCI, which might help?

```
Error: The Browser instance was closed either via `closeBrowser()` call, or it exited for reasons unknown to Taiko. You can try launching a fresh instance using `openBrowser()` or inspect the logs for details of the possible crash.
at errorMessageForBrowserProcessCrash (/home/circleci/librarian-gauge/node_modules/taiko/lib/browserLauncher.js:298:11)
at ChildProcess.browserExitEventHandler (/home/circleci/librarian-gauge/node_modules/taiko/lib/browserLauncher.js:312:49)
at Object.onceWrapper (events.js:421:26)
at ChildProcess.emit (events.js:314:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:276:12)
Error ----------------------------------

[Gauge]
js runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing


Your Environment Information -----------
	linux, 1.1.4, c982558
	html-report (4.0.12), js (2.3.12), screenshot (0.0.1)

Exited with code exit status 1
CircleCI received exit code 1

```

**Comment by markvillar** [comment]
Adding some delay before the start of the last step seem to have fixed the issue for us.

Since all our tests ends with the same Logout step:
javascript```
const { click, waitFor } = require('taiko');

step("Logout", { continueOnFailure: true}, async (done) => {

    //Add some delay here
    await waitFor(5000);

    await click("Logout");
    await done();

});
```

**Comment by Alenechka** [comment]
Facing the same issue. 
Gauge version: 1.1.4
Taiko 1.0.23 using Chrome(not Chromium)
OS Windows(run from terminal or VisualCode plugin)

```
Error: The Browser instance was closed either via `closeBrowser()` call, or it exited for reasons unknown to Taiko. You can try launching a fresh instance using `openBrowser()` or inspect the logs for details of the possible crash.
at errorMessageForBrowserProcessCrash (mypath\gauge\node_modules\taiko\lib\browserLauncher.js:298:11)
at ChildProcess.browserExitEventHandler (mypath\gauge\node_modules\taiko\lib\browserLauncher.js:312:49)
at Object.onceWrapper (events.js:422:26)
at ChildProcess.emit (events.js:315:20)
at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
Error ----------------------------------

[Gauge]
js runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

Get Support ----------------------------
	Docs:          https://docs.gauge.org
	Bugs:          https://github.com/getgauge/gauge/issues
	Chat:          https://spectrum.chat/gauge

Your Environment Information -----------
	windows, 1.1.4, c982558
	html-report (4.0.12), java (0.7.10), js (2.3.13), screenshot (0.0.1), spectacle (0.1.4), xml-report (0.2.3)
Error: Tests failed.
```

While running on ubuntu same versions of everything, there is no such error.

What I have tried:
runner_connection_timeout = 25000
runner_request_timeout = 25000
waitFor(5000) in the last step
waitFor(5000) in afterSuite
setTimeout(5000) in afterSuite

Only WA that helps is for example add waitFor without declaration(so i am having am error in afterSuite section in logs and report but everything else works fine). But it's a hack!
I am not able to run my test without erors and with a report in the same time.

Do you have any solution for this?
Should I reopen this issue or maybe create another one?

**Comment by zabil** [comment]
It's better to open another issue to track this as the original problem was with registering and unregistering listeners. Will help if you have some kind of an example in the new issue.
