### ISSUE TITLE
Provide a better error message when `ElementWrapperList` is passed to a Selector function

### ISSUE THREAD

**Issue by gdorsi** [getgauge/taiko#1366]
Hello there!
Thanks for providing this wonderful library!

I've run in this issue when trying to learn how to write tests with Gauge and Taiko.
I think that a self explainatory message would be helpful to get a better understanding on how to use selector functions.

### Expected behavior

Provide a more detailed error message when a wrong argument is passed to a `Selector` function.

I mean something like:

```
 * My spec  ...[FAIL]
        
        Failed Step: My spec
        Specification: specs/my.spec:8
        Error Message: TypeError: You are passing a `ElementWrapperList` to a `dropDown` selector. Refer https://docs.taiko.dev/api/dropdown/  for the correct parameters
        Stacktrace: 
        TypeError:  You are passing a `ElementWrapperList` to a `dropDown` selector. Refer https://docs.taiko.dev/api/dropdown/  for the correct parameters
            at xpath (node_modules/taiko/lib/helper.js:143:8)
            at node_modules/taiko/lib/taiko.js:2625:53
            at get (node_modules/taiko/lib/elementWrapper/elementWrapperFactory.js:64:56)
            at node_modules/taiko/lib/elementSearch.js:198:28
            at waitUntil (node_modules/taiko/lib/helper.js:121:17)
            at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

### Actual behavior
In a Gauge+Taiko project when `ElementWrapperList` is passed to a Selector function the resulting error is:

```
 * My spec  ...[FAIL]
        
        Failed Step: My spec
        Specification: specs/my.spec:8
        Error Message: TypeError: s.match is not a function
        Stacktrace: 
        TypeError: s.match is not a function
            at xpath (node_modules/taiko/lib/helper.js:143:8)
            at node_modules/taiko/lib/taiko.js:2625:53
            at get (node_modules/taiko/lib/elementWrapper/elementWrapperFactory.js:64:56)
            at node_modules/taiko/lib/elementSearch.js:198:28
            at waitUntil (node_modules/taiko/lib/helper.js:121:17)
            at processTicksAndRejections (internal/process/task_queues.js:93:5)
```

In the Taiko REPL the resulting error is:

```
Error: DropDown with label [object Object]  not found
```

### Steps to reproduce
1. Setup a Gauge + Taiko project
2. Write a `await dropDown($(selector)).select(value);` command inside a Gauge spec.
3. Run the spec

### Versions
```
node v12.13.0, taiko v1.0.13, @getgauge/cli v1.1.1
```

**Comment by NivedhaSenthil** [comment]
This seems a valid check to be done. Thanks for reporting and it would be great to have a PR raised.

**Comment by gdorsi** [comment]
Wow, thanks for the quick answer! I will try to work on this 😄
