### ISSUE TITLE
v1.0.19: Proximity selector does not find text ending on "*" anymore

### ISSUE THREAD

**Issue by klctrl** [getgauge/taiko#1455]
NOTE: The below Taiko code works fine in v1.0.16 - v1.0.18 but leads to an error in v1.0.19.

### Expected behavior
Proximity selector "below" (+ the others) finds element whose text ends on "*" (w/o the double-quotes), e.g. "Anrede *" -- like it does in Taiko v1.0.16 - v1.0.18.

### Actual behavior
Element is not found anymore, following error is produced for element with text "Anrede *":

> Error: Element with text Anrede * not found
    at findElements ([...]/node_modules/taiko/lib/elementSearch.js:230:11)
    at rectangle ([...]/node_modules/taiko/lib/taiko.js:3127:17)
    at RelativeSearchElement.findProximityElementRects ([...]/node_modules/taiko/lib/taiko.js:2604:17)
    at RelativeSearchElement.validNodes ([...]/node_modules/taiko/lib/proximityElementSearch.js:54:21)
    at getMatchingNode ([...]/node_modules/taiko/lib/proximityElementSearch.js:23:28)
    at handleRelativeSearch ([...]/node_modules/taiko/lib/proximityElementSearch.js:10:25)
    at _click ([...]/node_modules/taiko/lib/taiko.js:1119:17)
    at Object.click ([...]/node_modules/taiko/lib/taiko.js:1205:5)
    at Object.module.exports.<computed> [as click] ([...]/node_modules/taiko/lib/taiko.js:3266:14)

### Steps to reproduce
1. Create a web page with a button group of two buttons for the person's title and a label "Anrede *" above those two buttons, e.g. (German page):
![image](https://user-images.githubusercontent.com/68102896/91297208-3186fa80-e79e-11ea-9905-01399e0973d9.png)
2. Use the following Taiko code to select the button with the text "HERR": 
`await click('HERR', undefined, below('Anrede *'));`
3. Run the code.
4. Expect to see error "element not found".
5. Use the following Taiko code to select the button with the text "HERR":
`await click('HERR', undefined, below('Anrede'));`
6. Expect to see no error and button "HERR" getting selected.

### Versions
```
❯ npx taiko --version
Version: 1.0.19 (Chromium: 86.0.4229.0) RELEASE

❯ npx node --version
v14.7.0
```

**Comment by NivedhaSenthil** [comment]
could have been potentially fixed by https://github.com/getgauge/taiko/pull/1445, can you please check if there is a non-breaking space `&nbsp;` in the text ?

**Comment by klctrl** [comment]
@NivedhaSenthil Yes, there is a such non-breaking space in the text, see source code screenshot below.
![image](https://user-images.githubusercontent.com/68102896/91413043-db23c580-e84a-11ea-82bc-38887b7e6275.png)

**Comment by NivedhaSenthil** [comment]
Closing since a fix is done already.. we will releasing soon
