### ISSUE TITLE
With Firefox, cannot select any element in yahoo.com

### ISSUE THREAD

**Issue by navel3** [getgauge/taiko#1477]
### Expected behavior

Taiko can select elements in yahoo.com with firefox.

### Actual behavior

Taiko cannot select any element in yahoo.com with firefox.

### Steps to reproduce

*: The step 4 is optional.

1. $ TAIKO_BROWSER_PATH=\<path-to-firefox-nightly\> taiko
2. openBrowser()
3. goto('yahoo.com')
4. link('News').exists()
  Uncaught Cannot read property 'type' of undefined
5. focus(link('News'))  // takes few seconds...
  ✘ Error: Cannot read property 'type' of undefined, run `.trace` for more info.
6. .trace

```
"TypeError: Cannot read property 'type' of undefined
" +
  '    at getObjectIdsFromResult (/home/vagrant/.config/nvm/12.18.3/lib/node_modules/taiko/lib/handlers/runtimeHandler.js:30:46)
' +
  '    at Object.findElements (/home/vagrant/.config/nvm/12.18.3/lib/node_modules/taiko/lib/handlers/runtimeHandler.js:141:34)
' +
  '    at runMicrotasks (<anonymous>)
' +
  '    at processTicksAndRejections (internal/process/task_queues.js:97:5)
' +
  '    at async $function (/home/vagrant/.config/nvm/12.18.3/lib/node_modules/taiko/lib/elementSearch.js:206:5)
' +
  '    at async get (/home/vagrant/.config/nvm/12.18.3/lib/node_modules/taiko/lib/elementSearch.js:121:16)
' +
  '    at async Object.elements (/home/vagrant/.config/nvm/12.18.3/lib/node_modules/taiko/lib/elementSearch.js:255:47)
' +
  '    at async /home/vagrant/.config/nvm/12.18.3/lib/node_modules/taiko/lib/elementWrapper/linkWrapper.js:15:19
' +
  '    at async get (/home/vagrant/.config/nvm/12.18.3/lib/node_modules/taiko/lib/elementWrapper/helper.js:62:50)
' +
  '    at async /home/vagrant/.config/nvm/12.18.3/lib/node_modules/taiko/lib/elementSearch.js:249:22'

```

### Versions
```
Taiko: Version: 1.0.21 (Chromium: 86.0.4229.0) RELEASE
Firefox: Mozilla Firefox 82.0a1
```

**Comment by NivedhaSenthil** [comment]
Thanks for reporting, I could see the issue happening with latest firefox nightly. Will try fixing this

**Comment by navel3** [comment]
I can select elements in yahoo.com with the latest version.
Thank you.
