### ISSUE TITLE
Browser closed when click print button

### ISSUE THREAD

**Issue by dewirosalin** [getgauge/taiko#1579]
**Describe the bug**
Browser suddenly closed when click a button that has window.print() in it.

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Click Print button

```
const { openBrowser, click, closeBrowser, goto, button, reload } = require('taiko');
openBrowser();
goto("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_print");
click(button("Print this page"));
```

**Logs**

```
Failed Step: Print
        Specification: specs\specs.spec:5
        Error Message: TypeError: Cannot read property 'message' of undefined
        Stacktrace:
        TypeError: Cannot read property 'message' of undefined
            at node_modules\taiko\lib\taiko.js:121:19
            at processTicksAndRejections (internal/process/task_queues.js:97:5)
            at async Proxy.<anonymous> (node_modules\taiko\lib\taiko.js:107:18)
            at async node_modules\taiko\lib\taiko.js:3182:5
            at async doActionAwaitingNavigation (node_modules\taiko\lib\doActionAwaitingNavigation.js:60:5)
            at async waitForMouseActions (node_modules\taiko\lib\taiko.js:3176:3)
            at async _click (node_modules\taiko\lib\taiko.js:1213:5)
            at async click (node_modules\taiko\lib\taiko.js:1253:5)
            at async module.exports.<computed> (node_modules\taiko\lib\taiko.js:3330:14)
            at async Object.<anonymous> (tests\steps.js:16:5)


  Error Message: Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
  Stacktrace:
  Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
      at validate (node_modules\taiko\lib\taiko.js:3255:11)
      at module.exports.closeBrowser (node_modules\taiko\lib\taiko.js:323:3)
      at module.exports.<computed> (node_modules\taiko\lib\taiko.js:3330:36)
      at Object.<anonymous> (tests\steps.js:9:11)
```

**Expected behavior**
Browser still open with print dialogue and move to next step

**Versions:**
 - Taiko: 1.0.24
 - Win 10 version 1909
 - Node.js v.12.18.4

```
Gauge version: 1.1.1
Commit Hash: 6e0d83f

Plugins
-------
html-report (4.0.12)
js (2.3.12)
screenshot (0.0.1)
```

**Comment by msharma-tw** [comment]
Hi @zabil - can you please assign this issue to me?

**Comment by zabil** [comment]
I think this is fixed in the latest Taiko versions.

```
➜  taiko git:(master) cat test-script.js
const { openBrowser, goto, button, click, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_print");
        await click(button("Print this page"));
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
➜  taiko git:(master) taiko test-script.js
 ✔ Browser opened
 ✔ Navigated to URL https://www.w3schools.com/jsref/tryit.asp?filename=tryjsref_print
 ✔ Clicked button with label Print this page  1 times
 ✔ Browser closed
➜  taiko git:(master) taiko --version
Version: 1.0.26 (Chromium: 87.0.4279.0) 18c51705cec8114f1da25b1cd2e9b12c719f84fe
```

Please upgrade Taiko and see if you still face the issue.

**Comment by dewirosalin** [comment]
Hi zabil,

It works perfectly on headless mode. But when I set headless to false it gave me this error

```
TypeError: Cannot read property 'message' of undefined
    at C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:92:19
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
    at async Proxy.<anonymous> (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:78:18)
    at async simulateMouseClick (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\handlers\inputHandler.js:172:3)
    at async C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\actions\click.js:34:55
    at async doActionAwaitingNavigation (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\doActionAwaitingNavigation.js:60:5)
    at async simulateInputEvents (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\actions\click.js:33:5)
    at async click (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\actions\click.js:60:5)
    at async module.exports.click (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:1094:16)
    at async module.exports.<computed> (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:3098:14)
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
    at validate (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:3023:11)
    at module.exports.closeBrowser (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:291:3)
    at module.exports.<computed> (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:3098:36)
    at global.<computed> (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\bin\runFile.js:38:37)
    at C:\Users\dewir\Documents\test-taiko\test-script.js:10:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
Error: Connection to browser lost. This probably isn't a problem with Taiko, inspect logs for possible causes.
    at validate (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:3023:11)
    at module.exports.closeBrowser (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:291:3)
    at module.exports.<computed> (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\lib\taiko.js:3098:36)
    at global.<computed> (C:\Users\dewir\Documents\test-taiko\node_modules\taiko\bin\runFile.js:38:37)
    at C:\Users\dewir\Documents\test-taiko\test-script.js:10:15
    at processTicksAndRejections (internal/process/task_queues.js:97:5)
```
and it stops the other followed scenario.

**Comment by zabil** [comment]
Here's the output on the latest version 1.0.26 in non headless mode. Can you please make sure that you are using the latest version

<img width="1017" alt="Screenshot 2020-11-06 at 08 51 51" src="https://user-images.githubusercontent.com/54427/98346108-6f5d9600-200d-11eb-8dea-4dfbfcd6228a.png">

**Comment by dewirosalin** [comment]
Yes, I have used the latest version here.

![image](https://user-images.githubusercontent.com/70673557/98348421-b0789900-2053-11eb-8806-57d4e92b5bdf.png)

**Comment by NivedhaSenthil** [comment]
I could see the issue too ...will try fixing it 👍
