### ISSUE TITLE
Unable to find/change slider

### ISSUE THREAD

**Issue by klhex** [getgauge/taiko#1671]
**Describe the bug**
I've got a page with two sliders and Taiko seems unable to find them (and change their value):
![image](https://user-images.githubusercontent.com/71178731/98590571-52f08080-22cf-11eb-8379-0a76402fc7dd.png)

I've tried several approaches for finding the first slider (id: 'loanAmount', selectHiddenElements, proximity selector (above, below)) but I always get a "Error: Range ... not found".

The page's relevant source code:
```
<div class="o-layout u-mb">
   <div class="o-layout__item u-1/2 u-1/1@s">
      <div class="u-text-center"><label class="c-range-slider__infohead" for="loanAmount">Kreditwunsch</label></div>
      <div class="o-split"><label for="loanAmount">1.000</label><label for="loanAmount">50.000</label></div>
      <div id="loanAmount" class="c-custom-range-slider c-custom-range-slider__target c-custom-range-slider--left-to-right c-custom-range-slider--horizontal undefined">
         <div class="c-custom-range-slider__base">
            <div class="c-custom-range-slider__connect-container">
               <div class="c-custom-range-slider__connect" style="transform: translate(0%, 0px) scale(0.102041, 1);"></div>
            </div>
            <div class="c-custom-range-slider__origin" style="transform: translate(-897.959%, 0px); z-index: 4;">
               <div class="c-custom-range-slider__thumb c-custom-range-slider__thumb--lower" data-handle="0" tabindex="0" role="slider" aria-orientation="horizontal" aria-valuemin="1000.0" aria-valuemax="50000.0" aria-valuenow="6000.0" aria-valuetext="6000">
                  <div class="c-custom-range-slider__touch-area"></div>
               </div>
            </div>
         </div>
      </div>
      <div class="u-text-center"><output class="c-range-slider__output" for="loanAmount">6.000&nbsp;€</output></div>
   </div>
   <div class="o-layout__item u-1/2 u-1/1@s">
      <div class="u-text-center"><label class="c-range-slider__infohead" for="duration">Laufzeit</label></div>
      <div class="o-split"><label for="duration">12</label><label for="duration">120</label></div>
      <div id="duration" class="c-custom-range-slider c-custom-range-slider__target c-custom-range-slider--left-to-right c-custom-range-slider--horizontal undefined">
         <div class="c-custom-range-slider__base">
            <div class="c-custom-range-slider__connect-container">
               <div class="c-custom-range-slider__connect" style="transform: translate(0%, 0px) scale(0.666667, 1);"></div>
            </div>
            <div class="c-custom-range-slider__origin" style="transform: translate(-333.333%, 0px); z-index: 4;">
               <div class="c-custom-range-slider__thumb c-custom-range-slider__thumb--lower" data-handle="0" tabindex="0" role="slider" aria-orientation="horizontal" aria-valuemin="12.0" aria-valuemax="120.0" aria-valuenow="84.0" aria-valuetext="83.99999999999999">
                  <div class="c-custom-range-slider__touch-area"></div>
               </div>
            </div>
         </div>
      </div>
      <div class="u-text-center"><output class="c-range-slider__output" for="duration">84 Monate</output></div>
   </div>
</div>
```

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Go to ... (URL can be provided via mail or Spectrum Chat.)
2. Use Taiko's 'range' API to change the value of the sliders.
4. See error.

**Logs**

```
Error:  not found
    at RangeWrapper.firstElement (/[...]/node_modules/taiko/lib/elementWrapper/helper.js:8:11)
    at async RangeWrapper.select (/[...]/node_modules/taiko/lib/elementWrapper/rangeWrapper.js:63:18)

Error: Range above 6.000 not found
    at RangeWrapper.firstElement (/[...]/node_modules/taiko/lib/elementWrapper/helper.js:8:11)
    at async RangeWrapper.select (/[...]/node_modules/taiko/lib/elementWrapper/rangeWrapper.js:63:18)
    at async /[...]/slider.js:7:9
```

**Expected behavior**
Slider is found and its value is changed.

**Versions:**
 - Taiko: 1.0.26
 - OS 10.15.7 (19H2)
 - Node.js v14.13.1

**Comment by zabil** [comment]
Thanks for sharing the page source code. Taiko's `range` selector only works on [input type range](https://developer.mozilla.org/en-US/docs/Web/HTML/Element/input/range). It looks like you are trying to use `range` on a custom slider which does not use the correct input type.

As it is a custom control please use `evaluate` api to run a [script on the browser](https://docs.taiko.dev/running_scripts_inside_the_browser/) to select values.

**Comment by klhex** [comment]
@zabil Thanks for your feedback. The slider in question is indeed not an input type range one. Thanks for pointing me to the alternative solution via ```evalute```. In my case, since for my current tests I only need to change the slider to a different value than the initial one (since the test consists in validating the general functionality of the slider) and not to a specific value, I found out that I can achieve this via ```dragAndDrop```:
```
await dragAndDrop($('#loanAmount'), { right: 1 });
```
This moves the slider to the right (actually irregardless of the value of ```right```)  and thereby changes its value -- which is sufficient for my (smoke) test.
