### ISSUE TITLE
Tests fails when running many goto steps in succession

### ISSUE THREAD

**Issue by kskarra** [getgauge/taiko#1673]
Recently I've been working on a check of filters on a page, which is long series of goto and then it confirms the results on the page (in the next step). These basicly fails every run, usually within the first 10 (of a total of around 100) of the URL steps being loaded.
The step between each goto that checks that the page contains the expected results.
Is there a better/more correct way to set it up than the one below? The crash/error occurs on one of the goto-step every time.

**To Reproduce**
1. openBrowser() run
2. Do several (10+) goto steps in succession (doing different searches like the example below, with different text searches). 
3. See error

```
step(
'Search for conversations with <searchText> in date range <fromDate> - <toDate>',
async (searchText, fromDate, toDate) => {
try {
await goto(
${process.env.URL}/some_more_url?page=1&from_date=${fromDate}&to_date=${toDate}&conversation_text=${searchText}&visited_url_criteria=starts_with,
{
waitUntil: 'networkidle0',
}
);
} catch (e) {
console.error('Some fitting error message');
}
}
);

**Logs**

TypeError: Cannot read property 'exceptionDetails' of undefined
at getObjectIdsFromResult (/home/ubuntu/adminpanel/tests/node_modules/taiko/lib/handlers/runtimeHandler.js:36:21)
at Object.findElements (/home/ubuntu/adminpanel/tests/node_modules/taiko/lib/handlers/runtimeHandler.js:155:34)
at async $function (/home/ubuntu/adminpanel/tests/node_modules/taiko/lib/elementSearch.js:241:5)
at async get (/home/ubuntu/adminpanel/tests/node_modules/taiko/lib/elementSearch.js:154:16)
at async Object.elements (/home/ubuntu/adminpanel/tests/node_modules/taiko/lib/elementSearch.js:290:47)
at async TextWrapper._get (/home/ubuntu/adminpanel/tests/node_modules/taiko/lib/elementWrapper/textWrapper.js:25:9)
at async /home/ubuntu/adminpanel/tests/node_modules/taiko/lib/elementSearch.js:284:22
at async waitUntil (/home/ubuntu/adminpanel/tests/node_modules/taiko/lib/helper.js:126:11)
at async /home/ubuntu/adminpanel/tests/node_modules/taiko/lib/elementSearch.js:282:7
at async TextWrapper.elements (/home/ubuntu/adminpanel/tests/node_modules/taiko/lib/elementWrapper/elementWrapper.js:166:12)
Error ----------------------------------
[Gauge]
js runner quit unexpectedly. Check logs for more details.
ErrorMessage: transport is closing

**Expected behavior**
I would expect the URLs to be entered, pages to be loaded, and everything to look fine.

**Screenshots**
None.

**Versions:**
 - Taiko: 1.0.26
 - Node.js v15.1.0
 - OS; CircleCI ubuntu-1604:202010-01 - Ubuntu 16.04, Docker v19.03.13, Docker Compose v1.27.4
This also happens when I run it locally, also on Ubuntu 16.04.

13:16 $ gauge -v
Gauge version: 1.1.5
Commit Hash: f455126

Plugins
-------
html-report (4.0.12)
java (0.7.13)
js (2.3.14)
json-report (0.3.5)
screenshot (0.0.1)

**Comment by NivedhaSenthil** [comment]
there is a fix released as part of 1.0.27 ..can you please update and check

**Comment by kskarra** [comment]
The fix looks to have resolved the issue! Good work!

**Comment by NivedhaSenthil** [comment]
Thanks for the update 👍
