### ISSUE TITLE
Click element is covered by other element

### ISSUE THREAD

**Issue by dewirosalin** [getgauge/taiko#1679]
**Describe the bug**
I want to click specific text that covered by fixed element and I got this error. It was working before in older version (1.0.23)

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Goto gauge documentation page
2. Click "Step 3"
3. Click "Step 1"
4. Error element is covered by other element

```
const { openBrowser, write, closeBrowser, goto } = require('taiko');
openBrowser();
goto('https://docs.gauge.org/getting_started/create-test-project.html')
click('Step 3')
click('Step 1')
```

**Logs**

```
Error Message: Error: Element matching text "Step 1" is covered by other element
        Stacktrace: 
        Error: Element matching text "Step 1" is covered by other element
            at node_modules\taiko\lib\actions\pageActionChecks.js:116:11
            at async waitAndGetActionableElement (node_modules\taiko\lib\actions\pageActionChecks.js:91:3)
            at async click (node_modules\taiko\lib\actions\click.js:50:21)
            at async module.exports.click (node_modules\taiko\lib\taiko.js:1099:16)
            at async module.exports.<computed> (node_modules\taiko\lib\taiko.js:3107:14)
```

**Expected behavior**
As previous version, it will scroll and find the element without any problem

**Screenshots**
![taiko-1 0 23](https://user-images.githubusercontent.com/70673557/98907780-59af0b80-24fa-11eb-8aa0-b44bb5506fbe.png)
![taiko-1 0 28](https://user-images.githubusercontent.com/70673557/98907797-603d8300-24fa-11eb-930c-4d7345c556b3.png)

**Comment by NivedhaSenthil** [comment]
The difference in behavior seems to be happening because of 64eb6f6 .. scrolling the element before action was updated to nearest instead of center to avoid unnecessary scrolling. We might have to find a better way to tackle this scenario.
