### ISSUE TITLE
Selenoid Support fails on v1.0.28

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#1684]
Taiko was able to establish connection to Selenoid cluster with wsDebugUrl in v1.0.24. With the latest version it throws error 

```
ProtocolError: No target with given id found
    at /Users/Sai_Krishna_Vijaya_Kumar/Documents/git/taiko-selenoid/node_modules/chrome-remote-interface/lib/chrome.js:93:35
    at Chrome._handleMessage (/Users/Sai_Krishna_Vijaya_Kumar/Documents/git/taiko-selenoid/node_modules/chrome-remote-interface/lib/chrome.js:256:17)
    at WebSocket.<anonymous> (/Users/Sai_Krishna_Vijaya_Kumar/Documents/git/taiko-selenoid/node_modules/chrome-remote-interface/lib/chrome.js:234:22)
    at WebSocket.emit (events.js:314:20)
    at Receiver.receiverOnMessage (/Users/Sai_Krishna_Vijaya_Kumar/Documents/git/taiko-selenoid/node_modules/chrome-remote-interface/node_modules/ws/lib/websocket.js:825:20)
    at Receiver.emit (events.js:314:20)
    at Receiver.dataMessage (/Users/Sai_Krishna_Vijaya_Kumar/Documents/git/taiko-selenoid/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:437:14)
    at /Users/Sai_Krishna_Vijaya_Kumar/Documents/git/taiko-selenoid/node_modules/chrome-remote-interface/node_modules/ws/lib/receiver.js:394:23
    at /Users/Sai_Krishna_Vijaya_Kumar/Documents/git/taiko-selenoid/node_modules/chrome-remote-interface/node_modules/ws/lib/permessage-deflate.js:308:9
    at /Users/Sai_Krishna_Vijaya_Kumar/Documents/git/taiko-selenoid/node_modules/chrome-remote-interface/node_modules/ws/lib/permessage-deflate.js:387:7
    at afterWrite (_stream_writable.js:454:5)
    at onwrite (_stream_writable.js:434:7)
    at InflateRaw.afterTransform (_stream_transform.js:103:3)
    at Zlib.processCallback (zlib.js:588:8) {
  request: {
    method: 'Target.getTargetInfo',
    params: { targetId: '/devtools/e4a799fe2e8db2655a2d7e2a47faad64/page' }
  },
  response: { code: -32602, message: 'No target with given id found' }
}
```

**Comment by NivedhaSenthil** [comment]
Fixed via 1.1.0
