### ISSUE TITLE
Should be able to run test scripts in parallel

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#170]
**Expected behavior**
Should be able to run test scripts in parallel

**Actual behavior**
Getting the exception
```
node:1018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Target.targetCreated listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 2] (node:1018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 loadEventFired listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 2] (node:1018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Network.requestWillBeSent listeners added.Use emitter.setMaxListeners() to increase limit
(node:1018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Network.responseReceived listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 2] (node:1018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Target.targetCreated listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 2] (node:1018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Page.domContentEventFired listeners added.Use emitter.setMaxListeners() to increase limit
[runner: 2] (node:1018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Page.frameStartedLoading listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 2] (node:1018) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 Page.loadEventFired listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 1] (node:1015) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 loadEventFired listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 5] (node:1020) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 loadEventFired listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 7] (node:1014) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 loadEventFired listeners added. Use emitter.setMaxListeners() to increase limit
[runner: 2]   ## Get Started
[runner: 3]   ## Alert
[runner: 6] (node:1017) UnhandledPromiseRejectionWarning: Error: Link with text Roadmap  not found
    at elements (.../js-taiko/node_modules/taiko/lib/taiko.js:1490:15)
[runner: 6] (node:1017) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[runner: 6] (node:1017) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[runner: 4] (node:1019) UnhandledPromiseRejectionWarning: Error: Element with text "Plugins" not found
    at elements (.../js-taiko/node_modules/taiko/lib/taiko.js:1490:15)
[runner: 4] (node:1019) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
[runner: 4] (node:1019) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
[runner: 6] (node:1017) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 loadEventFired listeners added. Use emitter.setMaxListeners() to increase limit
```
**Steps to replicate**
* Run the gauge [js-taiko](https://github.com/getgauge-examples/js-taiko) project in parallel
> The above exception occurs

**Version**
```
commit - 0daea61fbeb29bcb78148721b95d98fec66d753d
```

**Comment by sguptatw** [comment]
My bad - js-taiko has node-modules with older taiko version. That was the problem. Freshly installing all node modules and running in parallel works as expected.

**Version**
```
commit - 0daea61fbeb29bcb78148721b95d98fec66d753d
```
