### ISSUE TITLE
should work seamlessly when installed as local module

### ISSUE THREAD

**Issue by NivedhaSenthil** [getgauge/taiko#172]
### Expected behavior
Should be able to run script using taiko runner when installing taiko as local module.

### Actual behavior
Does not give any message on the action done by script.

### Steps to reproduce
1. mkdir test
2. cd test
3. npm init
4. npm install git+https://github.com/getgauge/taiko.git --save
5. create code.js with below script

```
const { openBrowser, goto, write, press, near, checkBox, click, closeBrowser } = require('taiko');

(async () => {
    await openBrowser({headless:false});
    await goto("http://todomvc.com/examples/react/#/");
    await write("automate with taiko");
    await press("Enter");
    await click(checkBox(near("automate with taiko")));
    await closeBrowser();
})();
```
6.  ./node_modules/.bin/taiko code.js

The script runs successfully but no logs are printed by runner, if run in headless mode there is no clue if the script actually ran.

**Comment by sguptatw** [comment]
Local installation in Windows is failing to execute
```
 Error Message: Error: Failed to launch chrome!
    [0925/113622.477:ERROR:main_dll_loader_win.cc(134)] Failed to load Chrome DLL from C:\go\pipelines\Taiko\js-taiko\node_modules\taiko\.local-chromium\win64-571040\chrome-win32\chrome.dll: The specified module could not be found. (0x7E)

    Stacktrace: 
    Error: Failed to launch chrome!
    [0925/113622.477:ERROR:main_dll_loader_win.cc(134)] Failed to load Chrome DLL from node_modules\taiko\.local-chromium\win64-571040\chrome-win32\chrome.dll: The specified module could not be found. (0x7E)

        at onClose (node_modules\taiko\lib\browserFetcher.js:189:24)
        at ChildProcess.helper.addEventListener (node_modules\taiko\lib\browserFetcher.js:178:70)
        at ChildProcess.emit (events.js:160:13)

    Error Message: Error: Browser or page not initialized. Call `openBrowser()` before using this API
    Stacktrace: 
    Error: Browser or page not initialized. Call `openBrowser()` before using this API
        at validate (node_modules\taiko\lib\taiko.js:1629:30)
        at module.exports.closeBrowser (node_modules\taiko\lib\taiko.js:146:5)
        at Object.afterScenario (tests\step_implementation.js:13:32)
```
https://build.gauge.org/go/tab/build/detail/Taiko/265/specs/1/windows-specs

**Comment by NivedhaSenthil** [comment]
Above issue is tracked as part of #195
