### ISSUE TITLE
Plugin not working with TS

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#1762]
When I was adding taiko plugin to TS Taiko project I'm getting this error - TSError: ⨯ Unable to compile TypeScript:
test/performance/performance.spec.ts:1:43 - error TS2305: Module '"taiko"' has no exported member 'diagnostics'.

1 import { openBrowser, goto, closeBrowser, diagnostics } from "taiko";
                                            ~~~~~~~~~~~

    at createTSError (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/ts-node/src/index.ts:513:12)
    at reportTSError (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/ts-node/src/index.ts:517:19)
    at getOutput (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/ts-node/src/index.ts:752:36)
    at Object.compile (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/ts-node/src/index.ts:968:32)
    at Module.m._compile (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/ts-node/src/index.ts:1056:42)
    at Module._extensions..js (internal/modules/cjs/loader.js:962:10)
    at Object.require.extensions.<computed> [as .ts] (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/ts-node/src/index.ts:1059:12)
    at Module.load (internal/modules/cjs/loader.js:798:32)
    at Function.Module._load (internal/modules/cjs/loader.js:711:12)
    at Module.require (internal/modules/cjs/loader.js:838:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at Object.exports.requireOrImport (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/mocha/lib/esm-utils.js:20:12)
    at Object.exports.loadFilesAsync (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/mocha/lib/esm-utils.js:33:34)
    at singleRun (/Users/saikrisv/git/twCatalyst/taiko-starterkit/node_modules/mocha/lib/cli/run-helpers.js:156:3)
npm ERR! Test failed.  See above for more details.

**Comment by zabil** [comment]
Looks like this is a problem with how Taiko extends these methods for plugins as typescript expects the types to be in https://github.com/getgauge/taiko/blob/master/types/taiko/index.d.ts which is static.

**Comment by CDFriend** [comment]
I'm using a plugin with Typescript as well and I'm running into the same issue. My workaround is to import the plugin in a Javascript module, then import that into my Typescript code. This eliminates the benefits of Typescript for my plugin though - are there any plans to address this in a later release of Taiko?

**Comment by saikrishna321** [comment]
@zabil @NivedhaSenthil Ping

**Comment by zabil** [comment]
Have you tried the following

```
import { openBrowser, goto, closeBrowser } from "taiko";
// @ts-ignore: Plugin
import { diagnostics } from "taiko";


async function test() {
      await diagnostics.startTracing();
};
```

I think this is probably the best way to use plugins in typescript without having to add the types in the .d.ts file.
