### ISSUE TITLE
Getting an exception when js-taiko tests are run in docker container

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#177]
**Expected behavior**
Should be able to run tests seamlessly

**Actual behavior**
Getting an exception
```
(node:180) UnhandledPromiseRejectionWarning: Error: not opened
    at WebSocket.send (/gauge/node_modules/ws/lib/WebSocket.js:359:18)
    at Chrome._enqueueCommand (/gauge/node_modules/chrome-remote-interface/lib/chrome.js:270:18)
    at Promise (/gauge/node_modules/chrome-remote-interface/lib/chrome.js:84:22)
    at new Promise (<anonymous>)
    at Chrome.send (/gauge/node_modules/chrome-remote-interface/lib/chrome.js:83:20)
    at Object.handler [as getDocument] (/gauge/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Chrome.<anonymous> (/gauge/node_modules/taiko/lib/taiko.js:41:60)
    at Chrome.emit (events.js:182:13)
    at Chrome._handleMessage (/gauge/node_modules/chrome-remote-interface/lib/chrome.js:259:18)
    at WebSocket._ws.on (/gauge/node_modules/chrome-remote-interface/lib/chrome.js:223:22)
(node:180) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:180) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

**Steps to replicate**
* clone the repository https://github.com/getgauge-examples/js-taiko
* cd js-taiko
* docker build -tag test
* docker run -t test
> The above exception occurs

**Version**
```
commit - eb776a3e0aac915c63c0a8a77c6de8ffc2ccfed8
```

**Comment by NivedhaSenthil** [comment]
Fix is done in js-taiko. There are few args which has to be added on chromium startup when running in docker. Update the taiko docs regarding the same.

```
openBrowser({args: [ 
     '--disable-gpu',
      '--disable-dev-shm-usage',
      '--disable-setuid-sandbox',
      '--no-first-run',
      '--no-sandbox',
      '--no-zygote',
      '--single-process']})
 ```
