### ISSUE TITLE
Regression in the write API

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#1777]
**Describe the bug**

The mocha tests for write api fails on the latest `master` version beed2ce

With the following error

```
$ mocha test test/unit-tests/write.test.js -R dot


  !․․․․․Invalid text value null, setting value to empty ''
․Invalid text value undefined, setting value to empty ''
․․․․․!․

  12 passing (5s)
  2 failing

  1) write
       into focused element:
     Error: is not writable
      at /taiko/lib/actions/pageActionChecks.js:178:11
      at async waitAndGetActionableElement (lib/actions/pageActionChecks.js:153:3)
      at async write (lib/actions/write.js:59:11)
      at async module.exports.write (lib/taiko.js:1036:16)
      at async module.exports.<computed> (lib/taiko.js:2604:14)
      at async Context.<anonymous> (test/unit-tests/write.test.js:84:5)

  2) write with hideText option
       should mask the text when writing to focused element:
     Error: is not writable
      at taiko/lib/actions/pageActionChecks.js:178:11
      at async waitAndGetActionableElement (lib/actions/pageActionChecks.js:153:3)
      at async write (lib/actions/write.js:59:11)
      at async Object.module.exports.write (lib/taiko.js:1036:16)
      at async Object.module.exports.<computed> [as write] (lib/taiko.js:2604:14)
      at async Context.<anonymous> (test/unit-tests/write.test.js:224:5)
```
**To Reproduce**
``` 
git pull origin master
mocha test test/unit-tests/write.test.js -R dot

git checkout 1743920 # A working revision where tests pass
mocha test test/unit-tests/write.test.js -R dot

git checkout 854119b764f1494966af425d8d591462b5d3b7c0 # Bad revision as per git bisect
Previous HEAD position was 1743920 Match input with placeholders (#1655)
HEAD is now at 854119b Selenoid support (#1709)
mocha test test/unit-tests/write.test.js -R dot
  ․․․․․․Invalid text value null, setting value to empty ''
․Invalid text value undefined, setting value to empty ''
․․․․․!․

  13 passing (4s)
  1 failing

  1) write with hideText option
       should mask the text when writing to focused element:
     Error: Element focused is not writable
      at ./taiko/lib/taiko.js:1289:11
      at async Object.module.exports.write (lib/taiko.js:1266:3)
      at async Object.module.exports.<computed> [as write] (lib/taiko.js:3090:14)
      at async Context.<anonymous> (test/unit-tests/write.test.js:224:5)
```

**Expected behavior**
The tests should pass

**Versions:**
```
taiko git:(master) node --version
v15.3.0

taiko git:(master) sw_vers
ProductName:	macOS
ProductVersion:	11.1
BuildVersion:	20C69
```

**Comment by saikrishna321** [comment]
@zabil After upgrading to v1.1.2 we are seeing our tests failing for the same reason. Not writable

**Comment by zabil** [comment]
Ok, so it's not just a problem on my machine. Can you share the version of Node Js you are using?

**Comment by saikrishna321** [comment]
v1.1.0 works fine. 
v14.8.0 node
 
Tested on Mac OS.

**Comment by zabil** [comment]
Yes. A git bisect pointed to this change 854119b764f1494966af425d8d591462b5d3b7c0 I did look at it but could not find any change related to `write` api

**Comment by zabil** [comment]
Ok a bit more digging and this test is flaky and that led me to the wrong git bisect for example here in this version it fails and then passes

```
➜  taiko git:(82dc361) mocha test test/unit-tests/write.test.js


  write
    ✓ into focused element (167ms)
    ✓ should enter emoji char into focused element (80ms)
    ✓ into input field text
    ✓ into input field by label (39ms)
    ✓ should fail for readonly field (1032ms)
    ✓ should convert number to string value
Invalid text value null, setting value to empty ''
    ✓ should convert null to empty string value
Invalid text value undefined, setting value to empty ''
    ✓ should convert undefined to empty string value
    ✓ should wait for element to be writable when selector is provided (161ms)
    ✓ should write into shadow dom element (52ms)
    write test on multiple similar elements
      ✓ should write into first writable element
      ✓ should reject if no element is writable (1031ms)

  write with hideText option
    1) should mask the text when writing to focused element
    ✓ should mask the text when writing into a selected element


  13 passing (4s)
  1 failing

  1) write with hideText option
       should mask the text when writing to focused element:
     Error: Element focused is not writable
      at /Users/zabilcm/Gauge/taiko/lib/taiko.js:1289:11
      at async Object.module.exports.write (lib/taiko.js:1266:3)
      at async Object.module.exports.<computed> [as write] (lib/taiko.js:3090:14)
      at async Context.<anonymous> (test/unit-tests/write.test.js:224:5)



➜  taiko git:(82dc361) mocha test test/unit-tests/write.test.js


  write
    ✓ into focused element (166ms)
    ✓ should enter emoji char into focused element (82ms)
    ✓ into input field text (39ms)
    ✓ into input field by label
    ✓ should fail for readonly field (1040ms)
    ✓ should convert number to string value (40ms)
Invalid text value null, setting value to empty ''
    ✓ should convert null to empty string value
Invalid text value undefined, setting value to empty ''
    ✓ should convert undefined to empty string value
    ✓ should wait for element to be writable when selector is provided (162ms)
    ✓ should write into shadow dom element (51ms)
    write test on multiple similar elements
      ✓ should write into first writable element
      ✓ should reject if no element is writable (1034ms)

  write with hideText option
    ✓ should mask the text when writing to focused element (143ms)
    ✓ should mask the text when writing into a selected element


  14 passing (4s)
```

**Comment by KarianneM** [comment]
The write also fails for me for v1.1.2 and v1.1.1. v1.1.0 works fine
I work on Windows with node version 12.18.3

**Comment by zabil** [comment]
It looks like this 1a18bbb might have caused the regression

**Comment by zabil** [comment]
@KarianneM @saikrishna321 I was able to get the test passing adding a `await focus(textbox(...))` before the calling `write(textbox)` Ideally this shouldn't be the case. But it looks like the textbox is being marked as non writable when it does not have focus. 

Can you check if this solved the problem?

**Comment by KarianneM** [comment]
Works in my case

**Comment by saikrishna321** [comment]
In my case it was write into tableCell. Will look into write API tomorrow to see if I can add a fix...

**Comment by KarianneM** [comment]
@saikrishna321 @zabil The focus works for my login screen. Further in the process at the search screen I get the same error as before.
![image](https://user-images.githubusercontent.com/71637638/104710906-f2dbe780-5720-11eb-91fe-fb346052d5a3.png)

**Comment by NivedhaSenthil** [comment]
Though I couldn't see the unit tests failing locally.. I guess that the changes made to wait for actionable element now fetches the auto focused element and then checks if it is writable whereas earlier the check was to continuously check the current focused item instead of checking the pre-selected auto focused element. Will try fixing this.
