### ISSUE TITLE
Could not compute box model

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#183]
**Expected behavior**
Should be able to execute tests seamlessly

**Actual behavior**
Getting the exception
```
{ Error: Could not compute box model.
    at _enqueueCommand (...\taiko\node_modules\chrome-remote-interface\lib\chrome.js:89:34)
    at Chrome._handleMessage (...\taiko\node_modules\chrome-remote-interface\lib\chrome.js:245:17)
    at WebSocket._ws.on (...\taiko\node_modules\chrome-remote-interface\lib\chrome.js:223:22)
    at WebSocket.emit (events.js:182:13)
    at Receiver._receiver.onmessage (...\taiko\node_modules\ws\lib\WebSocket.js:141:47)
    at Receiver.dataMessage (...\taiko\node_modules\ws\lib\Receiver.js:389:14)
    at perMessageDeflate.decompress (...\taiko\node_modules\ws\lib\Receiver.js:349:40)
    at _decompress (...\taiko\node_modules\ws\lib\PerMessageDeflate.js:306:9)
    at _inflate.flush (...taiko\node_modules\ws\lib\PerMessageDeflate.js:386:7)
    at afterWrite (_stream_writable.js:493:3)
  request: { method: 'DOM.getBoxModel', params: { nodeId: 881 } },
  response: { code: -32000, message: 'Could not compute box model.' } }
```
**Steps to replicate**
> Observed on Windows. This error is intermittent. You may have to run it multiple times to observe
* Run the following script a few times
```
const { browser, openBrowser, goto, click,link,image } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("https://in.bookmyshow.com/bengaluru");

        await click("Bengaluru");
        await write('NCR', into(await inputField({"placeholder":"Search for your city"})));
        await click("NCR");
        await click("View All");
        await click(link("English"),below('Select Language'))
        await click(image(below(link("Now Showing"))))
        await click(link("Book Tickets"))

        await click(link({"class":"__showtime-link"}))
        await click("Accept")

        await click("Select Seats")
        await click(link(toRightOf("D")))
    } catch (e) {
        await screenshot()
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
**Version**
```
commit - 09afc93da99da144aa002a91feb1bd4b44506010
```

**Comment by BugDiver** [comment]
@sguptatw  I'm not able to replicate this with the latest version (commit Hash 0d5d17c). 
Can you verify if it still exists?

**Comment by nagendraprasadps1** [comment]
I had this issue when the page is not completely loaded. Issue vanished after waiting for an element using exists.
