### ISSUE TITLE
Error: not opened

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#184]
**Expected behavior**
Should execute seamlessly

**Actual behavior**
Getting error not opened
> Observed on Windows
```
Error: not opened
    at WebSocket.send (...\taiko\node_modules\ws\lib\WebSocket.js:359:18)
    at Chrome._enqueueCommand (...\taiko\node_modules\chrome-remote-interface\lib\chrome.js:270:18)
    at Promise (...\taiko\node_modules\chrome-remote-interface\lib\chrome.js:84:22)
    at new Promise (<anonymous>)
    at Chrome.send (...\taiko\node_modules\chrome-remote-interface\lib\chrome.js:83:20)
    at Object.handler [as getDocument] (...\taiko\node_modules\chrome-remote-interface\lib\api.js:32:23)
    at Chrome.<anonymous> (...\taiko\lib\taiko.js:43:60)
    at Chrome.emit (events.js:182:13)
    at Chrome._handleMessage (...\taiko\node_modules\chrome-remote-interface\lib\chrome.js:259:18)
    at WebSocket._ws.on (...\taiko\node_modules\chrome-remote-interface\lib\chrome.js:223:22)
```
**Steps to replicate**
> Observed on Windows
* Run the following script
```
const { browser, openBrowser, goto, click,comboBox } = require('taiko');
const assert = require('assert');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("google.com");
        await click("I'm Feeling Lucky");
        await click(link("About"));
        await comboBox({"id":"lang-chooser"}).select("‪हिन्दी‬");
        await click("Doodles संग्रह");
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
> Getting the above error

**Version**
```
commit - 09afc93da99da144aa002a91feb1bd4b44506010
```

**Comment by NivedhaSenthil** [comment]
Fix should be available in 1ae0cbc. That was happening because some listeners on page were running after closeBrowser, closing page before closing CRI connection handles it.
