### ISSUE TITLE
TimeField unit tests failing on Node.js 14.15.4

### ISSUE THREAD

**Issue by CDFriend** [getgauge/taiko#1852]
**Describe the bug**

Some of the unit tests for the TimeField selector appear to be failing. The expected date is off by 1 from the actual date. 

```
  1) timeField
       input with type date
         with inline text
           test select():

      AssertionError: expected '2018-09-11' to equal '2018-09-12'
      + expected - actual

      -2018-09-11
      +2018-09-12
```

Since Node 14 is the current LTS version, it might be worthwhile to run the unit tests under Node 14 in CI. 

**To Reproduce**

To repro, run: 

```
> npm run test
```

**Logs**

```
PS D:\dev\taiko> npm test 

> taiko@1.2.0 test D:\dev\taiko
> npm run test:api && npm run test:unit:silent


> taiko@1.2.0 test:api D:\dev\taiko
> node test/unit-tests/taiko-test.js

[PASS] All the exported functions are present in metadata

> taiko@1.2.0 test:unit:silent D:\dev\taiko
> mocha 'test/unit-tests/**/*.test.js' --timeout 6000 -R dot --trace-warnings



  ...........................................,.....,..,.........................................................................................,...................
  ............................................................................................................................,....,...,.....,......................
  .....................................................,,,,,,..,....................................................................................................
  ..................................................................................................................................................................
  ..................................................................................................................................................................
  ...................................................................................................................,.......,...............,................!....!
  ....!.....!...!...!...............................................................................................................................................
  ....

  1114 passing (39s)
  18 pending
  6 failing

  1) timeField
       input with type date
         with inline text
           test select():

      AssertionError: expected '2018-09-11' to equal '2018-09-12'
      + expected - actual

      -2018-09-11
      +2018-09-12

      at Context.<anonymous> (test\unit-tests\timeField.test.js:149:66)

  2) timeField
       input with type date
         wrapped in label
           test select():

      AssertionError: expected '2018-09-11' to equal '2018-09-12'
      + expected - actual

      -2018-09-11
      +2018-09-12

      at Context.<anonymous> (test\unit-tests\timeField.test.js:178:68)

  3) timeField
       input with type date
         using label for
           test select():

      AssertionError: expected '2018-09-11' to equal '2018-09-12'
      + expected - actual

      -2018-09-11
      +2018-09-12

      at Context.<anonymous> (test\unit-tests\timeField.test.js:205:64)

  4) timeField
       input with type date
         attribute and value pair
           test select():

      AssertionError: expected '2018-09-11' to equal '2018-09-12'
      + expected - actual

      -2018-09-11
      +2018-09-12

      at Context.<anonymous> (test\unit-tests\timeField.test.js:257:16)

  5) timeField
       input with type date
         with relative selector
           test select():

      AssertionError: expected '2018-09-11' to equal '2018-09-12'
      + expected - actual

      -2018-09-11
      +2018-09-12

      at Context.<anonymous> (test\unit-tests\timeField.test.js:282:71)

  6) timeField
       input with type date
         test elementsList properties
           test select():

      AssertionError: expected '2018-09-11' to equal '2018-09-12'
      + expected - actual

      -2018-09-11
      +2018-09-12

      at Context.<anonymous> (test\unit-tests\timeField.test.js:314:48)



npm ERR! code ELIFECYCLE
npm ERR! errno 6
npm ERR! taiko@1.2.0 test:unit:silent: `mocha 'test/unit-tests/**/*.test.js' --timeout 6000 -R dot --trace-warnings`
npm ERR! Exit status 6
npm ERR!
npm ERR! Failed at the taiko@1.2.0 test:unit:silent script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\charlief\AppData\Roaming\npm-cache\_logs\2021-02-09T17_20_29_911Z-debug.log
npm ERR! Test failed.  See above for more details.
PS D:\dev\taiko>
```

**Versions:**

 **OS:** Windows 10 20H2
**Node.js version:** 14.15.4
**Taiko Version:** Version: 1.2.0 (Chromium: 88.0.4314.0) RELEASE
**Taiko version hash:** f4d5b2aa2687a88550d11a139866cfd00b37d480

**Comment by NivedhaSenthil** [comment]
Tests passes fine me with `v14.15.5` and `v15.3.0`..probably we should be updating node versions in Github actions

**Comment by NivedhaSenthil** [comment]
Closing since our github actions runs on 14 too
