### ISSUE TITLE
Cannot find context with specified id

### ISSUE THREAD

**Issue by arijit91** [getgauge/taiko#2203]
Running into this error while running tests

```
Error: Cannot find context with specified id
    at /app/node_modules/chrome-remote-interface/lib/chrome.js:94:35
    at Chrome._handleMessage (/app/node_modules/chrome-remote-interface/lib/chrome.js:257:17)
    at WebSocket.<anonymous> (/app/node_modules/chrome-remote-interface/lib/chrome.js:235:22)
    at WebSocket.emit (node:events:369:20)
    at WebSocket.emit (node:domain:470:12)
    at Receiver.receiverOnMessage (/app/node_modules/ws/lib/websocket.js:834:20)
    at Receiver.emit (node:events:369:20)
    at Receiver.emit (node:domain:470:12)
    at Receiver.dataMessage (/app/node_modules/ws/lib/receiver.js:437:14)
    at /app/node_modules/ws/lib/receiver.js:394:23
```

This is on Taiko version `1.2.1` so may be different from the similar issue reported in https://github.com/getgauge/taiko/issues/1370 around Runtime.getProperties

The error goes away with this patch in `lib/handlers/runtimeHandler.js`

```
-    runtimeResult = await runtime.callFunctionOn(options);
+    try {
+      runtimeResult = await runtime.callFunctionOn(options);
+    } catch (e) {
+      if (e && e.message && e.message.includes('Cannot find context with specified id')) {
+        if (executionContextId) {
+          executionContextIds = executionContextIds.filter((id) => id !== executionContextId);
+        }
+      } else {
+        throw e;
+      }
+    }
```

Looks like we are ignoring the error in other places but not here.

**Comment by v1605** [comment]
I'm also experiencing this issue as of 1.2.6 . In our case it seems to occur intermittently after an interaction on the page causes a nested iframe to reload.
