### ISSUE TITLE
Dependency issue with remark-html >= 13.0.1

### ISSUE THREAD

**Issue by mhp-borisbojic** [getgauge/taiko#2311]
**Describe the bug**
remark-html has an security audit, therefore it's recommended to use remark-html >= 13.0.1.

When adding it to the resolution dependencies, a yarn / npm install will fail.

**To Reproduce**

Try to install taiko with remark-html >= 13.0.1

**Logs**

```
/Users/borisbojic/Development/myaftersal/myaftersal-servicebooking-ui/node_modules/taiko: Command failed.
Exit code: 1
Command: node lib/documentation.js
Arguments: 
Directory: /Users/borisbojic/Development/myaftersal/myaftersal-servicebooking-ui/node_modules/taiko
Output:
internal/modules/cjs/loader.js:1089
      throw new ERR_REQUIRE_ESM(filename, parentPath, packageJsonPath);
      ^

Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /Users/borisbojic/Development/myaftersal/myaftersal-servicebooking-ui/node_modules/remark-html/index.js
require() of ES modules is not supported.
require() of /Users/borisbojic/Development/myaftersal/myaftersal-servicebooking-ui/node_modules/remark-html/index.js from /Users/borisbojic/Development/myaftersal/myaftersal-servicebooking-ui/node_modules/documentation/src/output/util/formatters.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename index.js to end in .cjs, change the requiring code to use import(), or remove "type": "module" from /Users/borisbojic/Development/myaftersal/myaftersal-servicebooking-ui/node_modules/remark-html/package.json.

    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1089:13)
    at Module.load (internal/modules/cjs/loader.js:937:32)
    at Function.Module._load (internal/modules/cjs/loader.js:778:12)
    at Module.require (internal/modules/cjs/loader.js:961:19)
    at require (internal/modules/cjs/helpers.js:92:18)
    at Object.<anonymous> (/Users/borisbojic/Development/myaftersal/myaftersal-servicebooking-ui/node_modules/documentation/src/output/util/formatters.js:2:14)
    at Module._compile (internal/modules/cjs/loader.js:1072:14)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1101:10)
    at Module.load (internal/modules/cjs/loader.js:937:32)
```

**Expected behavior**
Package install should be possible with remark-html >= 13.0.1

**Screenshots**

**Versions:**
 - Taiko: 1.2.7
 - OS: macOS 11.5.2
 - Node.js v14.17.6

**Comment by zabil** [comment]
Thanks for reporting this. 
Remark is a dependency by the [documentation](https://documentation.js.org/) project. Taiko uses `documentation` command line to create API documentation. The API documentation creating process does not use markdown or remark. There is no threat from this as the moment as the vulnerability is an XSS vulnerability on un-sanitised user input. This can wait for an upstream fix made to the documentation project as the error comes from this lib.
