### ISSUE TITLE
Browser closes (Inspector.detached) on calling the page.close command

### ISSUE THREAD

**Issue by ankurnarkhede** [getgauge/taiko#2338]
**Describe the bug**
I am trying to run the taiko tests on chrome v93 another machine with OS MacOS Catalina. The function `pageHandler.closePage()` causes the browser to close and thus disconnecting the active websocket connections. I haven't been able to reproduce it in local machine, but got this error on multiple remote MacOS machines.

**To Reproduce**
Steps (or script) to reproduce the behavior:
1. Run your script on any remote MacOS machine.
2. Call `closeBrowser()` function in your script.
3. The browser gets closed and thus the WS connections are closed, thereby giving timeout error for the tests.
4. Logs
```
Client to browser:: {"id":15,"method":"Page.close","params":{}}
Browser to client:: {"id":15,"result":{}}
Browser to client:: {"method":"Inspector.detached","params":{"reason":"target_closed"}}
 err: websocket: close 1006 (abnormal closure): unexpected EOF 
```

```
const { openBrowser, write, closeBrowser, goto } = require('taiko');
openBrowser();
goto('...')
closeBrowser()
```

**Logs**
```
Client to browser:: {"id":15,"method":"Page.close","params":{}}
Browser to client:: {"id":15,"result":{}}
Browser to client:: {"method":"Inspector.detached","params":{"reason":"target_closed"}}
 err: websocket: close 1006 (abnormal closure): unexpected EOF 
```
```
WARNING: Browser or page not initialized. Call `openBrowser()` before using this API

  Error Message: Error: Timed out
  Stacktrace: 
  Error: Timed out
      at Timeout.<anonymous> (/Users/ankurnarkhede/.gauge/plugins/js/2.3.17/src/test.js:44:23)
      at listOnTimeout (internal/timers.js:557:17)
      at processTimers (internal/timers.js:500:7)

```

**Expected behavior**
The browser and the WS connections shouldn't get closed on calling page.close.

**Versions:**
 - Taiko: v1.2.7
 - OS : MacOS Catalina, Mojave
 - Node.js: v14

**Additional context**
I tried commenting out the `pageHandler.closePage()` function from node_modules that was causing it here: https://github.com/getgauge/taiko/blob/master/lib/connection.js#L131 , after that it seems so work fine as execpeted.

**Comment by ankurnarkhede** [comment]
cc: @NivedhaSenthil

**Comment by zabil** [comment]
It looks like the newer versions of chrome is closing the browser for macos on remote machines 
https://github.com/getgauge/taiko/blob/dec13ae3db953cd6c9cd6d20bcb4273138ccd32e/lib/connection.js#L130-L131

Can you send a PR with the line removed to check is the tests pass?

**Comment by saikrishna321** [comment]
@ankurnarkhede Thanks for reporting. I tried to replicate it locally and couldn't. 

Config: 

```
  "taiko": {
    "chromium_revision": "925089",
    "chromium_version": "96.0.4655.0"
  },

node version -  v16.X

```

**Comment by ankur-lt** [comment]
@saikrishna321 , yes, as per I mentioned in the issue description,  I haven't been able to reproduce it in local machine, but got this error on multiple remote MacOS machines.

**Comment by ankurnarkhede** [comment]
@saikrishna321 , yes, as per I mentioned in the issue description, I haven't been able to reproduce it in local machine, but got this error on multiple remote MacOS machines.

**Comment by zabil** [comment]
>  but got this error on multiple remote MacOS machines.

Can you explain a bit more about this setup? How do you run the tests in them?

**Comment by ankurnarkhede** [comment]
@zabil , we are starting a browser session on remote machine in debugger mode after getting the taiko openBrowser request. The client connects with the remote machine using the WS connection provided. The above error is received after every page.close command on the remote machines.
