### ISSUE TITLE
[FAIL] Error: Chromium revision is not downloaded. Provide TAIKO BROWSER PATH or Install taiko again to download bundled chromium., run .trace for more info

### ISSUE THREAD

**Issue by shaifaliyadav** [getgauge/taiko#2383]
Error: Chromium revision is not downloaded. Provide TAIKO_BROWSER_PATH or Install taiko again to download bundled chromium.
    at BrowserFetcher.getExecutablePath (node_modules/taiko/lib/browserFetcher.js:237:13)
    at launchBrowser (node_modules/taiko/lib/browserLauncher.js:324:44)
    at module.exports.openBrowser (node_modules/taiko/lib/taiko.js:95:65)
    at module.exports.<computed> (node_modules/taiko/lib/taiko.js:2612:36)
    at Context.beforeAll (setUp.js:93:11)
    at processTicksAndRejections (node:internal/process/task_queues:94:5)

It runs fine in docker mode.Tried installing-uninstalling/removing node_modules(whatever possible solutions availabe in google), but no luck.
From my understanding, it is not able to download the taiko dependencies locally(no idea why).
Any thoughts what is wrong or any other alternate way to fix this ?

**Comment by zabil** [comment]
This is being tracked at https://github.com/getgauge/taiko/issues/2235
