### ISSUE TITLE
SKIP_CHROMIUM_DOWNLOAD doesn't seem to skip chromium

### ISSUE THREAD

**Issue by honsq90** [getgauge/taiko#246]
Currently behind a corporate proxy and it doesn't seem to skip the chromium download even when I've specified the option

### Expected behavior

I'm running `SKIP_CHROMIUM_DOWNLOAD=true npm install taiko` but it doesn't seem to skip the chromium download.

I've tried it the following as well:
```
export SKIP_CHROMIUM_DOWNLOAD=true
npm install taiko
``` 

### Actual behavior

![image](https://user-images.githubusercontent.com/1791439/47541255-58ffa880-d924-11e8-9a18-e3e4e8bf5eda.png)

```
ERROR: Failed to download Chromium r594312! Set "SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.
{ Error: read ECONNRESET
    at _errnoException (util.js:1022:11)
    at TLSWrap.onread (net.js:615:25) code: 'ECONNRESET', errno: 'ECONNRESET', syscall: 'read' }
```

### Versions
```
node@v8.9.4
taiko@0.3.0
```

**Comment by NivedhaSenthil** [comment]
@honsq90 Thanks for reporting, will be fixing it soon.

**Comment by sguptatw** [comment]
**Discussion Updates**
All features of Taiko may not be available in other versions/executable. Support for Taiko features will be provided for the default bundled chromium. 

> Tech Notes: The current issue will be addressed with the following aspects in mind 
-`skip chromium download`
-`provide different host to download chromium`
-`provide executable path in case chromium is not downloaded`

**Comment by NivedhaSenthil** [comment]
Fix available in 8c4d653. 
Following env variable can be used now:
- SKIP_CHROMIUM_DOWNLOAD set to true to skip downloading chromium
- DOWNLOAD_HOST set to host url of mirror to download chromium
- EXECUTABLE_PATH set to launch browser from different location

**Comment by sguptatw** [comment]
Since these can be set as env variables, I think the names `DOWNLOAD_HOST ` and `EXECUTABLE_PATH ` should be more explicit like `CHROMIUM_DOWNLOAD_HOST` and `CHROMIUM_ EXECUTABLE_PATH`. 

Thoughts?

**Comment by sriv** [comment]
I think the environment variables used within taiko can use a `TAIKO_` prefix as well to avoid accidental name clash. It also makes it more traceable, IMO - i.e. knowing the source of an env variable.

**Comment by NivedhaSenthil** [comment]
Updated variable names as below,
- SKIP_CHROMIUM_DOWNLOAD to TAIKO_SKIP_CHROMIUM_DOWNLOAD
- DOWNLOAD_HOST to TAIKO_CHROMIUM_URL
- EXECUTABLE_PATH to TAIKO_BROWSER_PATH

Docs has to be updated with this new provision.

**Comment by anbalagank** [comment]
Hi I am seeing the ERROR: Failed to download Chromium r662092! Set "TAIKO_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

i used the command sudo npm install -g taiko  can you please let me know the exact command

**Comment by poornadeem** [comment]
Hi I am seeing the ERROR: Failed to download Chromium r662092! Set "TAIKO_SKIP_CHROMIUM_DOWNLOAD" env variable to skip download.

i used the command sudo npm install -g taiko can you please let me know the exact command

**Comment by nehashri** [comment]
@anbalagank @poornadeem Can you tell which OS you are facing this issue. What command did you run to install Taiko?

**Comment by poornadeem** [comment]
Hi @nehashri I am trying it in ubuntu box,
Command: sudo npm install -g taiko
2ndone:
sudo npm install -g taiko -skip chromium download

**Comment by polkowskijakub** [comment]
Same issue here - Ubuntu 19.04, I am trying: 
sudo npm install -g taiko

**Comment by NivedhaSenthil** [comment]
`TAIKO_SKIP_CHROMIUM_DOWNLOAD` is an env variable to be set before `npm install` like
`TAIKO_SKIP_CHROMIUM_DOWNLOAD=true npm install taiko`. Seems to work fine, do let us know if it does not.

**Comment by BernaGokce** [comment]
```sudo TAIKO_SKIP_CHROMIUM_DOWNLOAD=true npm install -g taiko```

<img width="779" alt="Screen Shot 2019-10-24 at 16 32 06" src="https://user-images.githubusercontent.com/17415636/67490511-057d8300-f67c-11e9-9fbc-b3e4bbfa625d.png">

**Comment by ninja18** [comment]
For me it got solved when I uninstalled and reinstalled node & npm  and then ran ```npm install -g taiko``` without sudo
