### ISSUE TITLE
Getting EACCES error on setting EXECUTABLE_PATH to an external folder where chromium is downloaded

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#253]
**Expected behavior**
Should be able to run tests with EXECUTABLE_PATH configured

**Actual behavior**
Getting error
```
{ Error: spawn <EXECUTABLE_PATH> EACCES
    at Process.ChildProcess._handle.onexit (internal/child_process.js:232:19)
    at onErrorNT (internal/child_process.js:407:16)
    at process._tickCallback (internal/process/next_tick.js:63:19)
  errno: 'EACCES',
  code: 'EACCES',
  syscall: 'spawn <EXECUTABLE_PATH>',
  path: '<EXECUTABLE_PATH>',
  spawnargs:
   [ '--remote-debugging-port=0',
     '--use-mock-keychain',
     '--user-data-dir=/var/folders/z0/w2x618g57yg1s2j8_c1g7k1m0000gp/T/taiko_dev_profile-tHGFva',
     '--headless',
     '--window-size=1440,900',
     '--disable-gpu',
     '--disable-dev-shm-usage',
     '--disable-setuid-sandbox',
     '--no-first-run',
     '--no-sandbox',
     '--no-zygote',
     '--single-process' ] }

    Error Message: Connection closed [127.0.0.1:49589] cause: EOF
    Stacktrace: 
    

    Error Message: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
    Stacktrace: 
    

  Error Message: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
  Stacktrace: 
  

# Browser Action
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
# Getting Started with Gauge
# Page Actions
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
# Proximity Selectors
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
# Selectors
Failed to initialize spec datastore. Error: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
# API

  Error Message: write tcp 127.0.0.1:49587->127.0.0.1:49589: use of closed network connection
```

**Steps to replicate**
* Download Chromium
* Copy the chromium folder to your desktop
* Set EXECUTABLE_PATH to your desktop
* execute js-taiko tests
> The above error occurs

> Blocks #246

**Comment by sriv** [comment]
`EACCESS` is most likely caused by the file permissions. Have you tried to launch the newly downloaded chromium outside taiko?

Chances are that you might need to do a `chmod` to add exec permissions for the user.

**Comment by sguptatw** [comment]
On Windows I gave the full permission as suggested in https://stackoverflow.com/questions/2928738/how-to-grant-permission-to-users-for-a-directory-using-command-line-in-windows

The permissions now is for Everyone
```
$> cacls ...\chrome-win
...\chrome-win Everyone:(OI)(CI)F
```
The contents also have full permission
```
...\chrome-win\72.0.3603.0.manifest Everyone:F

...\chrome-win\chrome.dll Everyone:F

...\chrome-win\chrome.exe Everyone:F

...\chrome-win\chrome_100_percent.pak Everyone:F

...\chrome-win\chrome_200_percent.pak Everyone:F

...\chrome-win\chrome_child.dll Everyone:F

...\chrome-win\chrome_elf.dll Everyone:F

...\chrome-win\chrome_watcher.dll Everyone:F

...\chrome-win\D3DCompiler_47.dll Everyone:F

...\chrome-win\elevation_service.exe Everyone:F

...\chrome-win\eventlog_provider.dll Everyone:F

...\chrome-win\First Run Everyone:F

...\chrome-win\icudtl.dat Everyone:F

...\chrome-win\interactive_ui_tests.exe Everyone:F

...\chrome-win\libEGL.dll Everyone:F

...\chrome-win\libGLESv2.dll Everyone:F

...\chrome-win\locales Everyone:(OI)(CI)F

...\chrome-win\MEIPreload Everyone:(OI)(CI)F

...\chrome-win\nacl_irt_x86_64.nexe Everyone:F

...\chrome-win\natives_blob.bin Everyone:F

...\chrome-win\notification_helper.exe Everyone:F

...\chrome-win\resources.pak Everyone:F

...\chrome-win\swiftshader Everyone:(OI)(CI)F

...\chrome-win\v8_context_snapshot.bin Everyone:F
```

However now I am getting error 
```
Error: Browser or page not initialized. Call `openBrowser()` before using this API
    at validate (...\js-taiko\node_modules\taiko\lib\taiko.js:1790:30)
    at module.exports.screenshot (C:\work\gauge\FT\js-taiko\node_modules\taiko\lib\taiko.js:908:5)
    at module.exports.(anonymous function) (C:\work\gauge\FT\js-taiko\node_modules\taiko\lib\taiko.js:1988:42)
    at gauge.screenshotFn (...\js-taiko\tests\step_implementation.js:21:18)
    at Object.capture (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-10-24\src\screenshot.js:27:13)
    at onError (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-10-24\src\executor.js:115:18)
    at _rejected (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-10-24\node_modules\q\q.js:864:24)
    at ...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-10-24\node_modules\q\q.js:890:30
    at Promise.when (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-10-24\node_modules\q\q.js:1142:31)
    at Promise.promise.promiseDispatch (...\AppData\Roaming\gauge\plugins\js\2.3.4.nightly-2018-10-24\node_modules\q\q.js:808:41)
```

**Comment by sguptatw** [comment]
Works as expected when chrome.exe path is set correctly. However, the error message `Failed to launch chrome!` is not visible when run from the gauge project when path is incorrect.

**Steps to replicate**
Same as the original issue

**Comment by NivedhaSenthil** [comment]
Observation:
when the executable is wrong openBrowser fails with message `Error Message: Error: Failed to launch chrome!` but as gauge tries to take custom screenshot on failure which again fails giving `Error: Browser or page not initialized. Call 'openBrowser()' before using this API` this is somehow ignoring the `failed to lauch chrome` error.
if custom screenshot is removed `Error Message: Error: Failed to launch chrome!` is shown

**Comment by NivedhaSenthil** [comment]
Error message hidden is handled in gauge-js now. Is there anything more pending for this issue ?

**Comment by sguptatw** [comment]
Since it was an issue in taiko, took only the latest of taiko and checked. It works as expected after updating the gauge-js plugin to `js (2.3.4.nightly-2018-11-20)`
