### ISSUE TITLE
Getting error `not opened`

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#262]
**Expected behavior**
Should be able to run taiko-gauge scenarios

**Actual behavior**
```
Error: not opened
    at WebSocket.send (...\gauge-e2e-taiko\node_modules\ws\lib\WebSocket.js:359:18)
    at Chrome._enqueueCommand (...\gauge-e2e-taiko\node_modules\chrome-remote-interface\lib\chrome.js:270:18)
    at Promise (...\gauge-e2e-taiko\node_modules\chrome-remote-interface\lib\chrome.js:84:22)
    at new Promise (<anonymous>)
    at Chrome.send (...\gauge-e2e-taiko\node_modules\chrome-remote-interface\lib\chrome.js:83:20)
    at Object.handler [as close] (...\gauge-e2e-taiko\node_modules\chrome-remote-interface\lib\api.js:32:23)
    at _closeBrowser (...\gauge-e2e-taiko\node_modules\taiko\lib\taiko.js:134:20)
    at Object.module.exports.closeBrowser (...\gauge-e2e-taiko\node_modules\taiko\lib\taiko.js:127:11)
    at Object.module.exports.(anonymous function) [as closeBrowser] (....\gauge-e2e-taiko\node_modules\taiko\lib\taiko.js:1987:42)
    at process.exitOnUnhandledFailures (...\gauge-e2e-taiko\node_modules\taiko\bin\taiko.js:16:45)
```
**Steps to replicate**
* checkout commit `a9b4177656b68f6110f56cf8ec259d2419c07c21` the repository https://github.com/sguptatw/gauge-e2e-taiko.git
* cd gauge-e2e-taiko
* npm install
* gauge run
> Observed on windows

**Version**
```
commit - 97d15d97306e595b3a7275df2077bf0a6a64856b
```

**Comment by NivedhaSenthil** [comment]
The above error was intermittently happening because there are no `await` for taiko actions like [here](https://github.com/sguptatw/gauge-e2e-taiko/blob/e59d79b6d15a0e9dcef4dcdd3f58e67a953d8258/tests/html-report.js#L64). After adding await for all taiko actions test suite works fine.

**Comment by sguptatw** [comment]
Thanks. But the problem is that in this case the error occurs multiple times and I have to restart the IDÈ/console to continue. 
Can that be addressed?

**Comment by sguptatw** [comment]
Thanks. But the problem is that in this case the error occurs multiple times and I have to restart the IDÈ/console to continue. 
Can that be addressed?
Can the error be displayed once and exit gracefully?

**Comment by NivedhaSenthil** [comment]
In this case no because there were many simultaneous taiko commands got triggered as there was no await and most of them failed, thats why there were multiple exceptions trying to perform action on closed tab.

**Comment by sguptatw** [comment]
The documentation can be more clear about which API is async and which is not. 
Currently, it is not clear from the examples also https://taiko.gauge.org/#elementwrapper. 
> Here the example of exists, proximity selectors etc don't show that the API is async.

One can get the above exception using the examples given in the docs.

On a side note it would help if functions like `exist` are sync.

**Comment by Apoorva-GA** [comment]
Docs have been updated as part of ea57c63.
