### ISSUE TITLE
Taiko does not install on Mac 

### ISSUE THREAD

**Issue by Venki-18** [getgauge/taiko#271]
When  I tried to install taiko on MAc OS 10.14.1, the install fails with the following error

usr/local/lib/node_modules/taiko/lib/browserFetcher.js:126
    async download(revision, progressCallback) {
          ^^^^^^^^
SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/taiko/lib/install.js:20:24)
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! taiko@0.3.0 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the taiko@0.3.0 install script.
**npm ERR! This is probably not a problem with npm. There is likely additional logging output above.**

### Versions
```
taiko@0.3.0   (latest version , install tried on 11/23/18
[taiko_install_error.txt](https://github.com/getgauge/taiko/files/2604876/taiko_install_error.txt)

node -> v6.11.0
```

**Comment by Venki-18** [comment]
Forgot to  mention, I've attached the detailed installation log

**Comment by NivedhaSenthil** [comment]
Currently taiko is not supported for node6. Can you please try upgrading the node version ?

**Comment by NivedhaSenthil** [comment]
Closing the issue as we do not have plans to support node6. Please feel free to open a new issue if you still face problem installing in upgraded node version.
