### ISSUE TITLE
Failed switching to target chrome 130

### ISSUE THREAD

**Issue by maxshifrin** [getgauge/taiko#2743]
**Describe the bug**
After switching the browser to chrome 130 stable, our automation became flakky. A lot of tests which ran thousands of times without error, are failing when trying to switch to a target (without a change to the underlying product)

Failed switching to target=/some_internal_path/
Error:Browser or page not initialized. Call `openBrowser()` before using this API
Stack: Error: Browser or page not initialized. Call `openBrowser()` before using this API
at validate (c:\Users\..\automation-tests-iso\..\taiko\lib\connection.js:175:11)
at module.exports.switchTo (c:\Users\..\..\node_modules\taiko\lib\taiko.js:205:3)
at module.exports.<computed> (c:\Users\..\..\node_modules\taiko\lib\taiko.js:2619:36)
at isSwitchedPage (c:\Users\..\..\taiko\BrowserActions.ts:20:31)
at waitForCondition (c:\Users\..\..\tests\utils\waitFor.ts:32:23)
at waitForHelper (c:\Users\..\..\tests\utils\waitFor.ts:19:5)
at BrowserActions.switchTo (c:\Users\..\..\tests\taiko\BrowserActions.ts:33:9)
at switchTabRegexUrl (c:\Users\....\tests\steps\PageActionsSteps.ts:208:9)

**To Reproduce**
Happens randomly

```
Error:Browser or page not initialized. Call `openBrowser()` before using this API
Stack: Error: Browser or page not initialized. Call `openBrowser()` before using this API
at validate (c:\Users\..\automation-tests-iso\..\taiko\lib\connection.js:175:11)
at module.exports.switchTo (c:\Users\..\..\node_modules\taiko\lib\taiko.js:205:3)
at module.exports.<computed> (c:\Users\..\..\node_modules\taiko\lib\taiko.js:2619:36)
at isSwitchedPage (c:\Users\..\..\taiko\BrowserActions.ts:20:31)
at waitForCondition (c:\Users\..\..\tests\utils\waitFor.ts:32:23)
at waitForHelper (c:\Users\..\..\tests\utils\waitFor.ts:19:5)
at BrowserActions.switchTo (c:\Users\..\..\tests\taiko\BrowserActions.ts:33:9)
at switchTabRegexUrl (c:\Users\....\tests\steps\PageActionsSteps.ts:208:9)
```

**Versions:**
 - Taiko: [e.g. 1.0.23 (use `taiko --version`)]
 - OS [e.g. 10.15.6 (19G2021) please be specific ]
 - Node.js [e.g. v.12.18.14]

```
gauge -v
Gauge version: 1.4.3
Commit Hash: f98dd40

Plugins
-------
html-report (4.3.1)
json-report (0.3.7)
screenshot (0.2.0)
spectacle (0.1.4)
ts (0.1.1)
```

**Comment by fhirter** [comment]
Having the same issue on taiko `Version: 1.4.1 (Chromium: 128.0.6597.0) RELEASE`.
Downgrading `Version: 1.3.10 (Chromium: 110.0.5478.0) RELEASE` solved the issue.

**Comment by kiranpatil-ic** [comment]
We also faced the same issue. For now we upgraded the chromium version to match 130 & so far everything is working well!

Until new version of taiko is released, you can go ahead & update the chromium version by doing the following :

- Navigate to node_modules/taiko/package.json
- Find & replace **_128.0.6597.0_** with **_130.0.6723.69_**
- Find & replace **1327306** with **1356014**
- In terminal execute 
```
cd node_modules/taiko
npm install
```
You should see a message saying updating chromium

**Comment by novafluxx** [comment]
Also encountered this issue beginning today. Tried Taiko 1.4.0 and has the same issue.

Even running the Chromium executable directly and browsing Wikipedia we encountered a crash.

We reverted to an older Taiko for now but will try to upgrade the Chromium version to the latest as @kiranpatil-ic suggested.

**Comment by zabil** [comment]
> Find & replace 128.0.6597.0 with 130.0.6723.69

@kiranpatil-ic can you please send a PR for this `package.json` modification?
