### ISSUE TITLE
Getting error Error: Invalid parameters on click

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#291]
**Expected behavior**
An action that I am able to perform in non-IFrame mode, I should be able to perform when the URL is rendered in an IFrame.

**Actual behavior**
Error: Invalid parameters (objectId: string value expected), run `.trace` for more info.

**Steps to replicate**
* Create a html file
```
<!DOCTYPE html>
<html>
<body>

<iframe src="https://gauge.org/index.html" width="750" height="750">
  <p>Your browser does not support iframes.</p>
</iframe>

</body>
</html>
```
* Open the REPL
```
> openBrowser()
[PASS] Browser opened
> goto("file:///.../iframe-html/renderAnotherURL.html",{timeout:60000})
[PASS] Navigated to url "file:///.../iframe-html/renderAnotherURL.html"
> click("Get Started")
[FAIL] Error: Invalid parameters (objectId: string value expected), run `.trace` for more info.
```
Where as
```
> openBrowser()
[PASS] Browser opened
> goto("getgauge.io",{timeout:60000})
[PASS] Navigated to url "http://getgauge.io"
> click("Get Started")
[PASS] Clicked element matching text "Get Started"
```
is successful

**Version**
```
commit - 62a7be8e75319fd3f8b3ca431af6f1f20ad63514
```
> Blocks #107

**Comment by NivedhaSenthil** [comment]
This was happening because of the viewport size, as in mobile view the "Get Started" in the menu is out of view port that scenario was not handled when checking if element is covered before clicking.
Fix available in 7cbcce8

**Comment by sguptatw** [comment]
## Getting this exception again
```
{ Error: Invalid parameters (type: string value expected; x: double value expected; y: double value expected)
    at _enqueueCommand (.../taiko/node_modules/chrome-remote-interface/lib/chrome.js:90:34)
    at Chrome._handleMessage (.../taiko/node_modules/chrome-remote-interface/lib/chrome.js:252:17)
    at WebSocket._ws.on (.../taiko/node_modules/chrome-remote-interface/lib/chrome.js:230:22)
    at WebSocket.emit (events.js:189:13)
    at Receiver.receiverOnMessage (.../taiko/node_modules/ws/lib/websocket.js:789:20)
    at Receiver.emit (events.js:189:13)
    at Receiver.dataMessage (.../taiko/node_modules/ws/lib/receiver.js:422:14)
    at perMessageDeflate.decompress (.../taiko/node_modules/ws/lib/receiver.js:379:23)
    at _decompress (.../taiko/node_modules/ws/lib/permessage-deflate.js:298:9)
    at _inflate.flush (.../taiko/node_modules/ws/lib/permessage-deflate.js:376:7)
  request: { method: 'Input.dispatchMouseEvent', params: 6000 },
  response:
   { code: -32602,
     message: 'Invalid parameters',
     data:
      'type: string value expected; x: double value expected; y: double value expected' } }
 ✔ Browser closed
```

**Steps to replicate**
* Execute the following script 
**Note**
This exception doesn't happen consistently. You may have to execute the following script multiple times to get the above exception 
```
const { openBrowser, goto, hover, click, button, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser({headless:false});
        await goto("http://automationpractice.com/index.php");
        await hover("Printed Dress");
        await click("Quick view",6000);
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by sguptatw** [comment]
Here the parameter of `click("Quick view", 6000);` is wrong. However can Taiko handle this better and show a message instead of throwing an exception

PS: Using `click("Quick view", {timeout:60000})` works as expected

**Comment by zabil** [comment]
The script works in version Taiko version 1.0.6
