### ISSUE TITLE
Cannot read property 'subtype' of undefined

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#294]
**Expected behavior**
Should be able to execute seamlessly without getting the error

**Actual behavior**
Getting the error
```
TypeError: Cannot read property 'subtype' of undefined
    at Object.getNodeIdsFromResult (/Users/sswaroop/work/gauge/others/taiko/lib/runtimeHandler.js:15:29)
    at getChildNodes (.../taiko/lib/taiko.js:331:45)
```
**Steps to replicate**
* Run the script
```
const { browser, openBrowser, goto, click,link,image } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("https://in.bookmyshow.com/bengaluru");

        await click("Bengaluru");
        await write('NCR', into(await inputField({"placeholder":"Search for your city"})));
        await click("NCR");
        await click("View All");
    } catch (e) {
        await screenshot()
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
**Version**
```
commit - 62a7be8e75319fd3f8b3ca431af6f1f20ad63514
```

**Comment by sguptatw** [comment]
Another example where I am getting the above error
```
const { browser, openBrowser, goto, listItem, click, link,image } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("https://gauge.org/index.html");
        await click(link("Blog"));

        await click(image(above(text('Zabil Maliackal'))))
        await waitFor("5000")
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```

**Comment by NivedhaSenthil** [comment]
Fix available on 
b2cd0e2
