### ISSUE TITLE
Getting Error: not opened

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#296]
**Expected behavior**
Should be able to execute seamlessly

**Actual behavior**
Getting error
```
Error: not opened
    at WebSocket.send (.../taiko/node_modules/ws/lib/WebSocket.js:359:18)
    at Chrome._enqueueCommand (.../taiko/node_modules/chrome-remote-interface/lib/chrome.js:270:18)
    at Promise (.../taiko/node_modules/chrome-remote-interface/lib/chrome.js:84:22)
    at new Promise (<anonymous>)
    at Chrome.send (.../taiko/node_modules/chrome-remote-interface/lib/chrome.js:83:20)
    at Object.handler [as continueInterceptedRequest] (.../taiko/node_modules/chrome-remote-interface/lib/api.js:32:23)
    at Chrome.handleInterceptor (.../taiko/lib/networkHandler.js:64:13)
    at Chrome.emit (events.js:182:13)
    at Chrome._handleMessage (.../taiko/node_modules/chrome-remote-interface/lib/chrome.js:259:18)
    at WebSocket._ws.on (.../taiko/node_modules/chrome-remote-interface/lib/chrome.js:223:22)
```

**Steps to replicate**
* Run the script
```
const { openBrowser, goto, write, press, link, click, near, checkBox, button, reload } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("http://todomvc.com/examples/react/#/");
        await write("something");
        await press("Enter");
	    await click(link("Active"));
	    await click(checkBox({'class':'toggle'},near('something')));
	    await click(link("Completed"));
	    await click(button("Clear completed"));
	    await reload("http://todomvc.com/examples/react/#/");
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
**Version**
```
commit - 62a7be8e75319fd3f8b3ca431af6f1f20ad63514
```

**Comment by NivedhaSenthil** [comment]
Fixed as part of d29e749.
