### ISSUE TITLE
Generate taiko api calls from the REPL

### ISSUE THREAD

**Issue by zabil** [getgauge/taiko#3]
After implementing #2  
Provide an option in the REPL to convert the sequence of REPL commands to taiko compatible API.

For e.g.

```
$ taiko
>> openBrowser
>> goto http://getgauge.io
>> click Get Started
>> .copy
```

should copy the following to clipboard

```
(async => {
 await openBrowser();
 await goto("http://getauge.io");
 await click("Get Started");
})();
```

**Comment by zabil** [comment]
This is now changed to 
```
$ taiko
>> openBrowser()
undefined
>> goto("https://getgauge.io")
undefined
>> click("Get Started")
undefined
>> closeBrowser()
undefined
>> .code
const { browser, page, openBrowser, closeBrowser, goto, reload, $, $$, link, listItem, inputField, textField, image, button, comboBox, checkBox, radioButton, alert, prompt, confirm, beforeunload, text, contains, click, doubleClick, rightClick, write, press, upload, highlight, focus, scrollTo, scrollRight, scrollLeft, scrollUp, scrollDown, hover, screenshot, timeoutSecs, intervalSecs, waitForNavigation, to, into } = require('taiko');

(async => {
    await openBrowser({headless: false});
    await goto("https://getgauge.io");
    await click("Get Started");
    await closeBrowser();
})();
>>
```

**Comment by zabil** [comment]
Modify the `.code` to take a filename
```
>> .code file.js
```
will save the code to a file

**Comment by BugDiver** [comment]
The command `.code` should capture only successful commands.

Example : 
```
➜  ~ taiko
>> openBrowser()
undefined
>> goto()
Error: Protocol error (Page.navigate): Invalid parameters url: string value expected
    at Session._onMessage (/usr/local/lib/node_modules/taiko/node_modules/puppeteer/lib/Connection.js:194:25)
    at Connection._onMessage (/usr/local/lib/node_modules/taiko/node_modules/puppeteer/lib/Connection.js:98:19)
    at emitOne (events.js:115:13)
    at WebSocket.emit (events.js:210:7)
    at Receiver._receiver.onmessage 
>> goto("https://getgauge.io")
undefined
>> .code
const { browser, page, openBrowser, closeBrowser, goto, reload, $, $$, link, listItem, inputField, textField, image, button, comboBox, checkBox, radioButton, alert, prompt, confirm, beforeunload, text, contains, click, doubleClick, rightClick, write, press, upload, highlight, focus, scrollTo, scrollRight, scrollLeft, scrollUp, scrollDown, hover, screenshot, timeoutSecs, intervalSecs, waitForNavigation, to, into } = require('taiko');

(async => {
	openBrowser();
	goto();
	goto("https://getgauge.io");
})();
>>
```

In above example, `.code` should not capture `goto()` action

**Comment by kashishm** [comment]
Implemented.
