### ISSUE TITLE
click api should waitForNavigation by default

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#32]
**Actual behavior**
Getting the following error
```
Error: Element not found
    at elements (/Users/sswaroop/work/gauge/others/taiko/lib/taiko.js:968:46)
(node:1503) UnhandledPromiseRejectionWarning: TypeError: browser is not a function
    at /Users/sswaroop/work/gauge/others/test/one/some.js:13:13
(node:1503) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1503) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
**Steps to replicate**
* Create a directory test
`git clone https://github.com/getgauge/taiko.git`
* Checkout branch taiko-cri
`git checkout taiko-cri`
* install taiko
npm install <fullPath> -g
* Create a testDirectory
Add a one.js file with 
```
const { browser, openBrowser, goto, click } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await click("I\'m Feeling Lucky");
        await click("About");
        await click("Doodles Archive");
    } catch (e) {
        console.error(e);
    } finally {
        if (browser()) {
            closeBrowser();
        }
    }
})();
```
* run this `taiko one.js`
> Getting the above error

**Version**
```
Version: 0.0.9 (HeadlessChrome/69.0.3452.0)
```
Parent #29

**Comment by sguptatw** [comment]
Work around
```
const { browser, openBrowser, goto, click } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("google.com");
        await click("I'm Feeling Lucky",{waitForNavigation:true});
        await click("About",{waitForNavigation:true});
        await click("Doodles Archive",{waitForNavigation:true});
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```

**Comment by nehashri** [comment]
I think the issue here is that waitForNavigation is set to false by default. We need to change this to true by default.

**Comment by Apoorva-GA** [comment]
Fix should be available in commit https://github.com/getgauge/taiko/commit/34d539bc06c2afa2e1b2b829747d6bbebfc367d5

**Comment by NivedhaSenthil** [comment]
Needs more things to be handled as simply making it default will make clicks without navigation to keep waiting for a navigation to happen.

**Comment by NivedhaSenthil** [comment]
Fix should be available in [commit](https://github.com/getgauge/taiko/commit/9cadd789d46c2635db8c0fca0e3ab64b532e1010)
