### ISSUE TITLE
Should be able to click a nested checkbox

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#33]
**Actual behavior**
Getting the error
```
TypeError: Cannot read property '0' of undefined
    at Object.check (/Users/sswaroop/work/gauge/others/taiko/lib/taiko.js:689:56)
```
**Steps to replicate**
* Create a directory test
`git clone https://github.com/getgauge/taiko.git`
* Checkout branch taiko-cri
`git checkout taiko-cri`
* install taiko
npm install <fullPath> -g
* Create a testDirectory
Add a todo.js file with 
```
const { browser, openBrowser, goto, link, click, listItem } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("http://todomvc.com/examples/react/#/");
        await click(link("Active"));
        await click(link("Completed"));
        await click(link("All"));
        await checkBox('something').check()
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
* run this `taiko todo.js`
> Getting the above error

**Version**
```
Version: 0.0.9 (HeadlessChrome/69.0.3452.0)
```
Blocks #29

**Comment by NivedhaSenthil** [comment]
The text 'something' belongs to li element, checking for checkbox near it should work 
`await checkBox('class','toggle',near('something')).check()` .

**Comment by sguptatw** [comment]
Getting the following error using the suggested change
```
TypeError: Cannot read property 'get' of undefined
    at isSelector (.../taiko/lib/taiko.js:1059:30)
    at elements (.../taiko/lib/taiko.js:1025:18)
    at elements (.../taiko/lib/taiko.js:1027:7)
    at element (.../taiko/lib/taiko.js:1020:49)
    at evaluate (.../taiko/lib/taiko.js:1096:40)
    at Object.check (.../taiko/lib/taiko.js:741:34)
(node:11082) UnhandledPromiseRejectionWarning: Error: Element not found
    at elements (.../taiko/lib/taiko.js:1028:46)
(node:11082) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:11082) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```
for the following code
```
const { browser, openBrowser, goto, link, click, listItem } = require('taiko');

(async () => {
    try {
        await openBrowser();
        await goto("http://todomvc.com/examples/react/#/");
        await write("something");
        await press("Enter");
        await click(link("Active"));
        await click(link("Completed"));
        await click(link("All"));

        await checkBox('class','toggle',near('something')).check()
        await reload("http://todomvc.com/examples/react/#/",{waitForNavigation:true});

        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```

**Comment by NivedhaSenthil** [comment]
```
(async () => {
        await openBrowser();
        await goto("http://todomvc.com/examples/react/#/");
        await inputField("placeholder","What needs to be done?").exists(intervalSecs(1), timeoutSecs(10));
        await focus(inputField("placeholder","What needs to be done?"));
        await write("something");
        await press("Enter");
        console.log(await checkBox("class","toggle",near("something")).exists());
        await click(checkBox("class","toggle",near("something")));
        console.log(await checkBox("class","toggle",near("something")).isChecked());
        await click("Active");
        await click("Completed");
        await reload("http://todomvc.com/examples/react/#/",{waitForNavigation:true});
        await closeBrowser();
   })();
```

This script works fine
