### ISSUE TITLE
Unable to select comboBox by ID

### ISSUE THREAD

**Issue by suleytron** [getgauge/taiko#356]
### Expected behavior
Should be able to select unique comboBox based on selectors

### Actual behavior
Unable to select the comboBox based on any of selectors 
e.g'

```
comboBox($('#Life_Required')).select('No')
Thrown: Combobox with label [object Object]  not found

comboBox($('#Life_Required')).exists()
 ✔ Does not Exist
(but this worked $('#Life_Required').exists()
 ✔ Exists)

comboBox(toRightOf($('#Life_Required'))).select('No')
Thrown: Combobox To Right of Custom selector $(#Life_Required) not found

workaround used
comboBox(toRightOf('Life Required')).select('Yes')

```
### Steps to reproduce
1. Webpage contains multiple comboBoxes
2. Try to select comboBox using selectors (workaround uses natural language worked as expected)
3. Unable to interact with comboBox base on ID.

### Versions
```
Version: 0.5.0 (Chromium:73.0.3638.0)
Node v8.15.0
```

**Comment by saikrishna321** [comment]
Code to reproduce:

```
const { openBrowser, goto, $, comboBox, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto('http://the-internet.herokuapp.com/dropdown');
        await comboBox($('#dropdown')).select('No')
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();

```

Debug Stack:

```
TypeError: s.match is not a function
    at xpath (/Users/saikrisv/git/taiko/lib/taiko.js:2104:17)
    at getElementGetter (/Users/saikrisv/git/taiko/lib/taiko.js:1407:77)
    at get (/Users/saikrisv/git/taiko/lib/taiko.js:1199:81)
    at /Users/saikrisv/git/taiko/lib/taiko.js:2078:38
    at Object.select (/Users/saikrisv/git/taiko/lib/taiko.js:1416:51)
    at repl:2:34

```

**Comment by NivedhaSenthil** [comment]
comboBox does not take another selector nested... any attribute value pair can be used like below
`await comboBox({id:'dropdown'}).select('Option 1')` should work in this case.
