### ISSUE TITLE
checkbox exists returns false even if element exists

### ISSUE THREAD

**Issue by mk654321** [getgauge/taiko#371]
### Expected behavior
checkbox().exists() returns false even if element exists, I guess this causes other functions not to work, eg checkbox().check() or checkbox().click
### Actual behavior
Tell us what happens instead

### Steps to reproduce
> openBrowser({args:['--no-sandbox', '--disable-setuid-sandbox']})
> goto("file:///.../checkbox.html")
 ✔ Navigated to url "file:///.../checkbox.html"

generic selector works fine:

> $(`#checkbox_terms_agree`).exists()
 ✔ Exists
> click($(`#checkbox_terms_agree`))
 ✔ Clicked custom selector $(#checkbox_terms_agree)
> click($(`#checkbox_terms_agree`))
 ✔ Clicked custom selector $(#checkbox_terms_agree)

now let's try checkbox selector:

> checkBox($(`#checkbox_terms_agree`)).check()
Thrown: 'Checkbox with label [object Object]  not found'
> checkBox($(`#checkbox_terms_agree`)).exists()
 ✔ Does not Exist
> click(checkBox($(`#checkbox_terms_agree`)))
 ✘ Error: Checkbox with label [object Object]  not found, run `.trace` for more info.
> .trace
Error: Checkbox with label [object Object]  not found
    at elements (/.../node_modules/taiko/lib/taiko.js:1796:15)
    at process.internalTickCallback (internal/process/next_tick.js:77:7)

### Versions
```
Paste `node` and `taiko` versions here.
node: 
v11.1.0
taiko:
Version: 0.5.0 (Chromium:73.0.3638.0)

```

### HTML
<html>
	<head><title>checkbox</title></head>
	<body>	
<label>
            <input type="checkbox"                     id="checkbox_terms_agree" name="agree" value="True"  />
            I agree to the terms          </label>
</body></html>

**Comment by mk654321** [comment]
My mistake - thank you for helpful clarification.
