### ISSUE TITLE
WebSocket is not open: readyState 3

### ISSUE THREAD

**Issue by varayal** [getgauge/taiko#405]
### Actual behavior

I'm facing below issue by using datatable. The first iteration works well but when starting the second iteration I got this error :(

➜  gauge -v
Gauge version: 1.0.4

Plugins
html-report (4.0.6)
js (2.3.4)
ruby (0.5.2)
screenshot (0.0.1)
spectacle (0.1.3)

➜  taiko -v
Version: 0.5.0 (Chromium:73.0.3638.0)

➜  node -v
v11.10.0

```
➜  front-linio-gauge gauge run -v specs/create_user.spec
(node:3206) DeprecationWarning: grpc.load: Use the @grpc/proto-loader module with grpc.loadPackageDefinition instead
# BOB User Creation

   |id|user|email        |
   |--|----|-------------|
   |1 |QA8 |qa8@test.com|
  ## Make sure the user is created
      * Goto X website	 ...[PASS]
      * Login with user and password	 ...[PASS]
      * Goto X menu	 ...[PASS]
      * Click on create a new user	 ...[PASS]
      * Fill <user> <email> and password into the form	 ...[PASS]
      * Click on save	 ...[PASS]

   |id|user|email        |
   |--|----|-------------|
   |2 |QA9 |qa9@test.com|
  ## Make sure the user is created
      * Goto X website	 ...[FAIL]

        Failed Step: Goto X website
        Specification: specs/create_user.spec:10
        Error Message: Error: WebSocket is not open: readyState 3 (CLOSED)
        Stacktrace:
        Error: WebSocket is not open: readyState 3 (CLOSED)
            at WebSocket.send (node_modules/ws/lib/websocket.js:322:19)
            at Chrome._enqueueCommand (node_modules/chrome-remote-interface/lib/chrome.js:277:18)
            at Promise (node_modules/chrome-remote-interface/lib/chrome.js:85:22)
            at new Promise (<anonymous>)
            at Chrome.send (node_modules/chrome-remote-interface/lib/chrome.js:84:20)
            at Object.handler [as navigate] (node_modules/chrome-remote-interface/lib/api.js:32:23)
            at module.exports.goto (node_modules/taiko/lib/taiko.js:486:28)
            at module.exports.(anonymous function) (node_modules/taiko/lib/taiko.js:2360:42)
            at Object.step (tests/step_implementation_1.js:17:11)
```

Any thoughts?

**Comment by NivedhaSenthil** [comment]
Please ensure the browser is not closed before completion of all actions, check if all actions are awaited properly before closeBrowser is called. This happens when we try to do action on a closed browser.

Wondering if the same test suite was working fine with the older version of taiko ?

**Comment by varayal** [comment]
Thanks @NivedhaSenthil I noticed I had a closeBrowser() on my last step defined. That was the reason why.
