### ISSUE TITLE
Should be able to select image with a proximity selector

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#44]
**Actual behavior**
Getting the following error
```
Error: String parameter expected
    at assertType (.../taiko/lib/taiko.js:1110:32)
    at module.exports.image.args (.../taiko/lib/taiko.js:508:5)    at global.(anonymous function) (.../taiko/taiko.js:27:36)
    at .../test/taikoTestCases/img.js:9:21
(node:16347) UnhandledPromiseRejectionWarning: Error: Element not found
    at elements (.../taiko/lib/taiko.js:1028:46)
(node:16347) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function witho
ut a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:16347) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will te
rminate the Node.js process with a non-zero exit code.
```

**Steps to replicate**
* Create a directory test
`git clone https://github.com/getgauge/taiko.git`
* Checkout branch taiko-cri
`git checkout taiko-cri`
* install taiko
npm install <fullPath> -g
* Create a testDirectory
Add a img.js file with 
```
const { browser, openBrowser, goto, listItem, click, link } = require('taiko');
const assert = require("assert");

(async () => {
    try {
        await openBrowser();
        await goto("https://gauge.org/index.html");
        await click(link("Blog"),{waitForNavigation:true});
        await click(image(above(text('Zabil Maliackal'))))
        await waitFor(5000);

        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
* run this `taiko img.js`
> Getting the above error

**Version**
```
Version: 0.0.9 (HeadlessChrome/69.0.3452.0)
```
Blocks #29

**Comment by Apoorva-GA** [comment]
Fix should be available in commit 6966ef450b5ca8a2c4aeba0814325ac34bc46501
