### ISSUE TITLE
When a windows or modal is closed it does not connect back to the existing tab

### ISSUE THREAD

**Issue by varayal** [getgauge/taiko#452]
Based on the fix https://github.com/getgauge/taiko/issues/427  I'm able to see the Paypal modal but after entering information and closed it. I noticed **taiko does not connect back to the existing tab**.

And I got the following error

   Error Message: Error: WebSocket is not open: readyState 3 (CLOSED)
   Stacktrace:
   Error: WebSocket is not open: readyState 3 (CLOSED)
       at WebSocket.send (node_modules/ws/lib/websocket.js:332:19)
       at Chrome._enqueueCommand (node_modules/chrome-remote-interface/lib/chrome.js:277:18)
       at Promise (node_modules/chrome-remote-interface/lib/chrome.js:85:22)
       at new Promise (<anonymous>)
       at Chrome.send (node_modules/chrome-remote-interface/lib/chrome.js:84:20)
       at Object.handler [as navigate] (node_modules/chrome-remote-interface/lib/api.js:32:23)
       at module.exports.goto (node_modules/taiko/lib/taiko.js:508:28)
       at module.exports.(anonymous function) (node_modules/taiko/lib/taiko.js:2317:42)
       at Object.afterScenario (tests/CL/cl_hook.js:24:11)

➜  taiko -v
Version: 0.7.0 (Chromium: 74.0.3723.0)

➜  gauge -v
Gauge version: 1.0.4
Commit Hash: 3a9a647

Plugins
-------
html-report (4.0.6)
js (2.3.4)
ruby (0.5.2)
screenshot (0.0.1)
spectacle (0.1.3)

**Comment by NivedhaSenthil** [comment]
fix available in 50515d7

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the version ```cc2c1dc ```
