### ISSUE TITLE
Cannot install taiko

### ISSUE THREAD

**Issue by MR-H0200** [getgauge/taiko#474]
```shell
$ npm install -g taiko
/usr/local/bin/taiko -> /usr/local/lib/node_modules/taiko/bin/taiko.js

> taiko@0.6.0 install /usr/local/lib/node_modules/taiko
> node lib/install.js

/usr/local/lib/node_modules/taiko/lib/browserFetcher.js:125
    async download(revision, progressCallback) {
          ^^^^^^^^

SyntaxError: Unexpected identifier
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (/usr/local/lib/node_modules/taiko/lib/install.js:20:24)
npm ERR! Darwin 18.2.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "taiko"
npm ERR! node v6.12.0
npm ERR! npm  v3.10.10
npm ERR! code ELIFECYCLE

npm ERR! taiko@0.6.0 install: `node lib/install.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the taiko@0.6.0 install script 'node lib/install.js'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the taiko package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node lib/install.js
npm ERR! You can get information on how to open an issue for this project with:
npm ERR!     npm bugs taiko
npm ERR! Or if that isn't available, you can get their info via:
npm ERR!     npm owner ls taiko
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/hari-zu427/npm-debug.log
```

**Comment by zabil** [comment]
Taiko only works on node versions 8 and above.
The node version in the logs posted above is 6. Please upgrade the node version and try again.
