### ISSUE TITLE
Meteor specific: calling Meteor.logout from evaluate() always results in error "No node with given id found"

### ISSUE THREAD

**Issue by dmolin** [getgauge/taiko#478]
### Expected behavior
Calling Meteor.logout() within an `evaluate` block (resulting in the browser navigating away from the current page) shouldn't trigger any error in the taiko test.

### Actual behavior
This is the situation: I'm using Meteor and, while trying to log out the current user, I execute this code:
```
step("Logout", async () => {
  await evaluate(() => Meteor.logout());
});
```
The call to `Meteor.lgout()` results in the browser navigating away from the current page (the reactive code in the client detects the user has logged out and redirect back to the login page).

I cannot say if the redirect is the issue here, but almost everytime I call this step I get an error from taiko that is preventing my test to complete:

```
Failed Step: Logout
        Specification: specs/logout.md:17
        Error Message: Error: No node with given id found
        Stacktrace: 
        Error: No node with given id found
            at _enqueueCommand (node_modules/chrome-remote-interface/lib/chrome.js:90:34)
            at Chrome._handleMessage (node_modules/chrome-remote-interface/lib/chrome.js:252:17)
            at WebSocket._ws.on (node_modules/chrome-remote-interface/lib/chrome.js:230:22)
            at emitOne (events.js:116:13)
            at WebSocket.emit (events.js:211:7)
            at Receiver.receiverOnMessage (node_modules/ws/lib/websocket.js:792:20)
            at emitOne (events.js:116:13)
            at Receiver.emit (events.js:211:7)
            at Receiver.dataMessage (node_modules/ws/lib/receiver.js:422:14)
```

More in general, this is an error I get in some occasions and I cannot fathom what causes it (it doesn't have any relationship with what my test is doing in the page). It seems to be this error is caused by an issue in the communication between Taiko and the browser but I cannot guess what I am supposed to do to avoid it. I perfectly understand this is a fringe issue (since it happens only with MeteorJS) but any help would be appreciated.

The only fix I've found so far is to put a try {} catch () block around the 'await evaluate()` call, since in the end I know the function call is working correctly (the user is logged out), but it definitely feels like a hack.

### Versions
```
node: 8.11.4
taiko: 0.6.0
```

**Comment by BugDiver** [comment]
@dmolin Not sure why it's happening. Could you provide some sample code/project which can help us to replicate the issue?

**Comment by NivedhaSenthil** [comment]
@dmolin any updates ?

**Comment by Apoorva-GA** [comment]
Closing due to inactivity. Please feel free to reopen.
