### ISSUE TITLE
Taiko repl does not handle js alerts set up

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#495]
### Expected behavior
Taiko repl should able to handle js alerts set up

### Actual behavior
Throwing error inconvenient error

### Steps to reproduce
1. openBrowser()
2. goto("http://the-internet.herokuapp.com/javascript_alerts");
3. confirm("I am a JS Confirm", async() => await dismiss());
Its throwing the below error:
``` 
Thrown:
TypeError: Cannot read property 'exists' of undefined
    at repl.context.(anonymous function) (/usr/local/Homebrew/lib/node_modules/taiko/lib/repl.js:215:25)
    at repl:2:9
    at repl:3:3
    at Script.runInContext (vm.js:135:20)
    at Object.defaultEval (repl.js:324:29)
    at bound (domain.js:400:14)
    at Object.runBound (domain.js:413:12)
```

### Versions
```
8e408c0909ca38fb2340fdc140aeffe6e94cb5bf
```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the commit version a622aa5c84bc8544ef3e3028ae73afcb55a96b1b
