### ISSUE TITLE
Auto scroll does not work while performing click action.

### ISSUE THREAD

**Issue by negiDharmendra** [getgauge/taiko#521]
### Expected behavior
User should be able to `click` on an element which is not visible on the browser viewport

### Actual behavior
User sees a below error:
 
    Object id doesn't reference a Node
      at _enqueueCommand (<project_path>/node_modules/chrome-remote-interface/lib/chrome.js:90:34)
      at Chrome._handleMessage (<project_path>/node_modules/chrome-remote-interface/lib/chrome.js:252:17)
      at WebSocket._ws.on (<project_path>/node_modules/chrome-remote-interface/lib/chrome.js:230:22)
      at WebSocket.emit (events.js:182:13)
      at Receiver.receiverOnMessage (<project_path>/node_modules/ws/lib/websocket.js:792:20)
      at Receiver.emit (events.js:182:13)
      at Receiver.dataMessage (<project_path>/node_modules/ws/lib/receiver.js:422:14)
      at perMessageDeflate.decompress (<project_path>/node_modules/ws/lib/receiver.js:379:23)
      at _decompress (<project_path>/node_modules/ws/lib/permessage-deflate.js:298:9)
      at _inflate.flush (<project_path>/node_modules/ws/lib/permessage-deflate.js:376:7)

### Steps to reproduce

    const { openBrowser, goto, click, closeBrowser } = require('taiko');
    (async () => {
       try {
          await openBrowser();
          await goto('https://mybiz.makemytrip.com/');
          await click('signup for free');
      } catch (e) {
          console.error(e);
      } finally {
          await closeBrowser();
      }
    })();

### Versions
```
Paste `node` and `taiko` versions here.
node : v10.11.0
taiko : Version: 0.7.0 (Chromium: 74.0.3723.0), commit: cc2c1dcb96868e4606710a0defcc233f2926e4c1 
```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed. Tested with the version ```9a876b8```
