### ISSUE TITLE
Should wait for load to complete before performing the action

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#555]
### Expected behavior
Should be able to find existing element on screen

### Actual behavior
Unable to find an element "Quick view"

### Steps to reproduce
* Execute script 
```
const { openBrowser, goto, hover, click, button, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser({headless:false});
        await goto("http://automationpractice.com/index.php");
        await hover("Printed Dress");
        await click("Quick view");
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
**Error**
```
Error: Element with text Quick view not found
```

**Notes**
```
Taiko tries to perform the action hover before the load is completed
```

### Versions
```
NodeJS - v10.15.3
Taiko commit - 3bb2ade397840ad2326026bb7fad840161e673ea
Version: 0.8.0 (Chromium: 74.0.3723.0)
```

**Comment by NivedhaSenthil** [comment]
Fix available in 471101e

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the commit version ```471101e```

**Comment by sguptatw** [comment]
Here is another example where the action is being performed before the page is loaded
```
const { openBrowser, goto, below, textBox, into, write, press, click, button, checkBox, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser({headless:false});
        await goto("cleartrip.com");
        await write("Bangalore, IN - Kempegowda International Airport (BLR)",into(textBox(below("From"))));
        await press("Enter");
        await write("New Delhi, IN - Indira Gandhi Airport (DEL)",into(textBox(below("To"))));
        await press("Enter");
        await click("24",below("June 2019"));
        await click("Search flights");
        await click(button("Search flights"));
        await click("Book");
    } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
Getting the error
```
Error: Element matching text "Book" is covered by other element
    at _click (/.../taiko/lib/taiko.js:757:15)
```
**Version**
```
commit - d4a99381515a3a6262f829eee79a8e00197ada05
```

**Comment by sguptatw** [comment]
Couple of observations here
- sometimes the test script does not execute beyond 
```
await write("New Delhi, IN - Indira Gandhi Airport (DEL)",into(textBox(below("To"))));
        await press("Enter");
```
Enter gets invoked before the previous operation is complete. There is an async load on the dropdown when text is being entered

- Sometimes it goes to the next page but fails to find the "book" element
> The script execution is flaky

**Comment by sguptatw** [comment]
Here is another example where the script execution is flaky.
```
const { openBrowser, goto, hover, click, button, closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser({headless:false});
        await goto("http://automationpractice.com/index.php");
        await hover("Printed Dress");
        await click("Quick view",{timeout:60000})
        await click("Add to Cart")
        await click("Proceed to checkout")
        await click("Proceed to checkout")
        await write("demo@thoughtworks.com",below("Email address"))
        } catch (e) {
        console.error(e);
    } finally {
        await closeBrowser();
    }
})();
```
> Getting error `Error: Element matching text "Proceed to checkout" is covered by other element
    at _click (.../taiko/lib/taiko.js:764:15)`

**Version**
```
commit - 7482e63f741fde16ff9fb9db5267b37dc51931e3
```
