### ISSUE TITLE
Getting error waitFor is not a function

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#59]
**Expected behavior**
Should be able to use API function waitFor https://taiko.gauge.org/#waitfor

**Actual behavior**
Getting error
```
TypeError: waitFor is not a function
    at .../test/taikoTestCases/todo-add.js:9:15
    at process._tickCallback (internal/process/next_tick.js:68:7)
```
**Steps to replicate**
* Run the following script using taiko
```
const { browser, openBrowser, goto, link, click, listItem,checkBox,waitFor } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("http://todomvc.com/examples/react/#/");
        await write("something");
        await press("Enter");  
        await waitFor(1000);
        await click(checkBox('class','toggle',near('something')))
        await hover(checkBox('class','toggle'))
        await closeBrowser();
    } catch (e) {
        console.error(e);
    } finally {
    }
})();
```
**Version**
```
commit version - ab73800e370f6afa5b50d223f1c92908c40fd696
```

**Comment by sguptatw** [comment]
When there is an error waitFor is not found,  the test hangs as well.

**Comment by NivedhaSenthil** [comment]
Seems to be working fine.
