### ISSUE TITLE
Error:  Cannot read property 'toString' of null

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#609]
### Expected behavior
After installing taiko from master, it should woks seamlessly. 

### Actual behavior
Throwing below error:
```
PS C:\Users\Debas\AppData\Roaming> taiko -v
TypeError: Cannot read property 'toString' of null
    at getExecutablePlugins (C:\Users\Debas\AppData\Roaming\npm\node_modules\taiko\lib\plugins.js:23:81)
    at Object.<anonymous> (C:\Users\Debas\AppData\Roaming\npm\node_modules\taiko\bin\taiko.js:69:19)
    at Module._compile (internal/modules/cjs/loader.js:721:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:732:10)
    at Module.load (internal/modules/cjs/loader.js:620:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:560:12)
    at Function.Module._load (internal/modules/cjs/loader.js:552:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:774:12)
    at executeUserCode (internal/bootstrap/node.js:342:17)
    at startExecution (internal/bootstrap/node.js:276:5)
```
**NOTE: This issue works fine in mac and specific to windows os. In release version it works fine**

### Steps to reproduce
1. Install taiko from master
2. run ```taiko -v``` or ```taiko```

### Versions
```
Commit: f079ec458fbc4b3f0d49333de853e9a188fa7a87
node version: v11.6.0
os: windows 10
```

**Comment by Debashis9012** [comment]
This issue has been verified and found fixed with the commit version ```f012f0670424b0e065564e09c3099c9eef6f71de ```
