### ISSUE TITLE
Cannot read property 'x' of undefined

### ISSUE THREAD

**Issue by sguptatw** [getgauge/taiko#650]
### Expected behavior
Should be able to execute script without encountering an exception 

### Actual behavior
Getting the exception 
```
TypeError: Cannot read property 'x' of undefined
    at click (.../taiko/lib/taiko.js:862:48)
    at module.exports.(anonymous function) (.../taiko/lib/taiko.js:2896:42)
    at global.(anonymous function) (.../taiko/bin/runFile.js:25:45)
    at .../taikoTestCases/clearTrip.js:28:15
```

### Steps to reproduce
1. Execute the script
```
const { openBrowser, goto, toLeftOf, radioButton, click, below, text, inputField, into, write, reload, focus, press, link, comboBox } = require('taiko');

(async () => {
    try {
        await openBrowser({headless:false});
        await goto("cleartrip.com");
        await focus(inputField(below(text("From"))));
        await write("Bangalore, IN - Kempegowda International Airport (BLR)",into(inputField(below(text("From")))),{delay:100});
        await press("Enter");
        await click(comboBox({"id":"Adults"}));
        await comboBox({"id":"Adults"}).select("2")
    } catch (e) {
        console.error(e);
    } finally {
        closeBrowser();
    }
})();
```
> The above exception occurs

### Versions
```
commit - 7a49c17886d51b619dcfa53717fd88518d6499dc
```

**Comment by NivedhaSenthil** [comment]
Couldn't replicate the issue, seeing the error message looks like it could happen only with `await click()` where no selector or coordinates is passed to click.

**Comment by sguptatw** [comment]
It is quite consistent for me with the above script.
This is how the execution details look like
```
✔ Browser opened
 ✔ Navigated to URL http://cleartrip.com
 ✔ Wrote Bangalore, IN - Kempegowda International Airport (BLR) into the text field Below From
 ✔ Pressed the Enter key
 ✔ Wrote New Delhi, IN - Indira Gandhi Airport (DEL) into the text field Below To
 ✔ Pressed the Enter key
TypeError: Cannot read property 'x' of undefined
    at click (.../taiko/lib/taiko.js:862:48)
    at module.exports.(anonymous function) (.../taiko/lib/taiko.js:2896:42)
    at global.(anonymous function) (.../taiko/bin/runFile.js:25:45)
    at .../taikoTestCases/clearTrip.js:28:15
 ✔ Browser closed
```

**Comment by sguptatw** [comment]
Yes, it is because of the wrong usage of the API
