### ISSUE TITLE
Getting error 'element focused is not writable' in gauge taiko project

### ISSUE THREAD

**Issue by kirtisingh16** [getgauge/taiko#682]
### Expected behavior
should be able to write in the focused field

### Actual behavior
getting error that the 'element focused is not writable'

### Steps to reproduce
1. `await focus(inputField({id:'input-4'},below('Template Name')));
    await write("FirstTemp", into(inputField({id:''input-4'},below('Template Name'))));`
2. this element is inside a frame

### Versions
```
Gauge version: 1.0.5
js (2.3.5)
node v10.16.0
taiko Version: 0.7.1 (Chromium: 74.0.3723.0) undefined
```

**Comment by sguptatw** [comment]
The taiko version used is very old. Can you please update to the latest and check if that issue persists.

**Comment by kirtisingh16** [comment]
> The taiko version used is very old. Can you please update to the latest and check if that issue persists.

Sure!!

**Comment by kirtisingh16** [comment]
> The taiko version used is very old. Can you please update to the latest and check if that issue persists.

I am trying to uninstall and then install the latest version of taiko but everytime the old version (Version: 0.7.1 (Chromium:74.0.3723.0) )is getting installed
using command to install is 'npm install -g taiko'
node version : v.12.6.0

**Comment by sguptatw** [comment]
Your project package json may have a taiko dependency on this specific version.
Please update and check.

**Comment by kirtisingh16** [comment]
> Your project package json may have a taiko dependency on this specific version.
> Please update and check.

I tried to run above commands in latest version (Version: 1.0.0 (Chromium: 76.0.3803.0) RELEASE) and still facing the same issue.

**Comment by luciferankon** [comment]
Could you please share a small html snippet which can help us to reproduce the issue?

**Comment by Apoorva-GA** [comment]
@kirtisingh16 Any updates on this?

**Comment by Apoorva-GA** [comment]
Closing this due to inactivity. Feel free to reopen if you are still facing the issue.

**Comment by gs-cavula** [comment]
Facing the same isue, it would be great some can help?

Error while executing the script
Error: Element focused is not writable
    at /usr/lib/node_modules/taiko/lib/taiko.js:1389:13
    at async _write (/usr/lib/node_modules/taiko/lib/taiko.js:1384:5)
    at async /usr/lib/node_modules/taiko/lib/taiko.js:1374:24
    at async doActionAwaitingNavigation (/usr/lib/node_modules/taiko/lib/taiko.js:3299:3)
    at async module.exports.write (/usr/lib/node_modules/taiko/lib/taiko.js:1344:3)
    at async module.exports.<computed> (/usr/lib/node_modules/taiko/lib/taiko.js:3542:14)
    at async global.<computed> (/usr/lib/node_modules/taiko/bin/runFile.js:44:15)
    at async /home/chandra/first.js:7:2

**Version:**
Version: 1.0.2 (Chromium:76.0.3803.0)

**Comment by zabil** [comment]
This happens on read only fields. 
Can share the Taiko script or html snippet on which this problem is happening?

**Comment by 1160545** [comment]
i am getting the same issue but i am having the latest version of taiko then also i am getting focused element is not writable. please help me as soon as possible
