### ISSUE TITLE
closeBrowser() fails on windows with assert error from rimraf

### ISSUE THREAD

**Issue by saikrishna321** [getgauge/taiko#837]
Error on `closeBrowser` api. The browser shuts but the test fails with below error.

```
assert(received)

    Expected value to be equal to:
      true
    Received:
      false

      at fixWinEPERM (node_modules/rimraf/rimraf.js:175:5)
      at node_modules/rimraf/rimraf.js:160:15


```

**Comment by Debashis9012** [comment]
This issue has been fixed.
Tested version: `Version: 1.0.2 (Chromium: 76.0.3803.0) 9b0b3fc46c78e2596c9dad34e9a0ce69abf3be30`
