### ISSUE TITLE
Is it possible to connect to a remote browser ?

### ISSUE THREAD

**Issue by GautierT** [getgauge/taiko#877]
Hi,

I would like to be able to connect to a remote docker containing a chrome browser. 
The docker is build with https://github.com/browserless/chrome. 

With puppeteer i connect to this instance like this : 
`await puppeteer.connect({ browserWSEndpoint: 'ws://remote_web_address.com:3000' });`

Is it possible to do the same with taiko ?

Thanks a lot for this awesome package !

**Comment by sriv** [comment]
hi @GautierT - you can pass `host` and `port` as options to [`openBrowser`](https://taiko.gauge.org/#openbrowser) in Taiko. 

Is this what you seek?

**Comment by GautierT** [comment]
Hi @sriv . 

I tried but when i pass https://remote_url.com as host and 443 as port it just hang and nothing happen... 
Could i pass directly the url to the websocket like with puppeteer to be able to connect to wss://remote_url.com/ ?

i think this is related to the `connect_to_cri` because when i do a console.log here i see a lot of `target : undefined` : 
```
const connect_to_cri = async target => {
  if (process.env.LOCAL_PROTOCOL) {
    localProtocol = true;
  }
  if (_client) {
    await network.setRequestInterception({ patterns: [] });
    _client.removeAllListeners();
  }
  return new Promise(async function connect(resolve) {
    try {
      console.log('target :', target)
      if (!target) {
        const browserTargets = await cri.List({
          host: currentHost,
          port: currentPort,
        });
```

**Comment by sriv** [comment]
Sorry for the delay @GautierT - I believe the `undefined` should lead to evaluation of the subsequent `if` block. The `currentHost` should be set to the `host` option passed (ref: https://github.com/getgauge/taiko/blob/master/lib/taiko.js#L207)

Do you, by any chance, have a dockerfile or a docker-compose setup for me to replicate the problem?

**Comment by saikrishna321** [comment]
@GautierT 

>https://remote_url.com as host and 443 as port

`host` is the machine IP where the chrome browser is opened and `port` remote-debugging-port

for ex: 

```
'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome' --remote-debugging-port=9222
```

**Comment by GautierT** [comment]
Ok so i openBrowser like this : 
```
await openBrowser({
      host: `remote_url.com`,
      port: 3000,
      //ignoreCertificateErrors: true,
    })
```
I added multiple console.log in `connect_to_cri` : 
```
....
return new Promise(async function connect(resolve) {
    try {
      console.log('target : ', target)
      if (!target) {
        console.log('no target')
        const browserTargets = await cri.List({
          host: currentHost,
          port: currentPort,
          // secure: true,
        });
        console.log('browserTargets : ', browserTargets)
        if (!browserTargets.length)
          throw new Error('No targets created yet!');
        target = browserTargets.filter(
          target => target.type === 'page',
        )[0];
        if (!target.length)
          throw new Error('No targets created yet!');
      }
      console.log('launching cri : ', target )
      await cri({ target, local: localProtocol }, async c => {
            _client = c;
.... 
```

The resulting console is : 
```
target :  undefined

no target

browserTargets :  [ { description: '',
    devtoolsFrontendUrl:
     '/devtools/inspector.html?ws=ip_address_of_the_server:3000/devtools/page/KnNaV8Xt',
    targetId: '/devtools/page/KnNaV8Xt',
    title: 'about:blank',
    type: 'page',
    url: 'about:blank',
    webSocketDebuggerUrl: 'ws://ip_address_of_the_server:3000/devtools/page/KnNaV8Xt' } ]

// From the catch block
e :  Error: No targets created yet!
    at connect (/Users/me/Documents/Projets/repo/node_modules/taiko/lib/taiko.js:102:17)
    at process._tickCallback (internal/process/next_tick.js:68:7)

target :  { description: '',
  devtoolsFrontendUrl:
   '/devtools/inspector.html?ws=ip_address_of_the_server:3000/devtools/page/KnNaV8Xt',
  targetId: '/devtools/page/KnNaV8Xt',
  title: 'about:blank',
  type: 'page',
  url: 'about:blank',
  webSocketDebuggerUrl: 'ws://ip_address_of_the_server:3000/devtools/page/KnNaV8Xt' }

launching cri :  { description: '',
  devtoolsFrontendUrl:
   '/devtools/inspector.html?ws=ip_address_of_the_server:3000/devtools/page/KnNaV8Xt',
  targetId: '/devtools/page/KnNaV8Xt',
  title: 'about:blank',
  type: 'page',
  url: 'about:blank',
  webSocketDebuggerUrl: 'ws://ip_address_of_the_server:3000/devtools/page/KnNaV8Xt' }
Error: Unexpected server response: 404
    at ClientRequest.req.on (/Users/me/Documents/Projets/repo/node_modules/ws/lib/websocket.js:595:7)
    at ClientRequest.emit (events.js:189:13)
    at ClientRequest.EventEmitter.emit (domain.js:441:20)
    at HTTPParser.parserOnIncomingClient [as onIncoming] (_http_client.js:556:21)
    at HTTPParser.parserOnHeadersComplete (_http_common.js:109:17)
    at Socket.socketOnData (_http_client.js:442:20)
    at Socket.emit (events.js:189:13)
    at Socket.EventEmitter.emit (domain.js:441:20)
    at addChunk (_stream_readable.js:284:12)
    at readableAddChunk (_stream_readable.js:265:11)
```

On browserless i have this logs : 
```
2019-10-15T13:51:45.967Z browserless:server { CONNECTION_TIMEOUT: 60000,
  MAX_CONCURRENT_SESSIONS: 10,
  QUEUE_LENGTH: 10,
  SINGLE_RUN: false,
  CHROME_REFRESH_TIME: 1800000,
  KEEP_ALIVE: false,
  DEFAULT_BLOCK_ADS: false,
  DEFAULT_HEADLESS: true,
  DEFAULT_LAUNCH_ARGS: [],
  DEFAULT_IGNORE_DEFAULT_ARGS: false,
  DEFAULT_IGNORE_HTTPS_ERRORS: false,
  DEFAULT_USER_DATA_DIR: undefined,
  PREBOOT_CHROME: false,
  CHROME_BINARY_LOCATION: '/usr/bin/google-chrome',
  DEBUG: 'browserless*',
  DEMO_MODE: false,
  ENABLE_CORS: false,
  ENABLE_DEBUGGER: true,
  ENABLE_DEBUG_VIEWER: true,
  ENABLE_XVBF: false,
  TOKEN: null,
  DISABLE_AUTO_SET_DOWNLOAD_BEHAVIOR: true,
  FUNCTION_BUILT_INS: [ 'url' ],
  FUNCTION_EXTERNALS: [ 'lighthouse', 'node-pdftk' ],
  WORKSPACE_DIR: '/usr/src/app/workspace',
  WORKSPACE_DELETE_EXPIRED: false,
  WORKSPACE_EXPIRE_DAYS: 30,
  FAILED_HEALTH_URL: null,
  QUEUE_ALERT_URL: null,
  REJECT_ALERT_URL: null,
  TIMEOUT_ALERT_URL: null,
  ERROR_ALERT_URL: null,
  EXIT_ON_HEALTH_FAILURE: false,
  MAX_CPU_PERCENT: 99,
  MAX_MEMORY_PERCENT: 99,
  METRICS_JSON_PATH: null,
  HOST: '0.0.0.0',
  MAX_PAYLOAD_SIZE: '5mb',
  PORT: 3000 } Final configuration
2019-10-15T13:55:25.696Z browserless:job SUwkqqfe0: /devtools/page/KnNaV8Xt: Inbound WebSocket request.
2019-10-15T13:55:25.697Z browserless:server /devtools/page/KnNaV8Xt: Couldn't load session for /devtools/page/KnNaV8Xt
```

Any idea why ?

P.S : [i opened an issue on browserless repo too](https://github.com/browserless/chrome/issues/396)

**Comment by saikrishna321** [comment]
@GautierT  Thanks for detail information. I can't connect to the WebSocket manually.

1. Pulled the docker image.
2. Visited `http://localhost:3000/json`
3. Took the `webSocketDebuggerUrl` and used a web-client to connect to the WebSocket URL and it failed with the below error.

```
2019-10-16T06:04:33.575Z browserless:server /devtools/page/597C7CB2DF49220F62B1B52B35BAA030: Couldn't load session for /devtools/page/597C7CB2DF49220F62B1B52B35BAA030
```

**Comment by GautierT** [comment]
Thanks for trying @saikrishna321.
@joelgriffith from [Browserless](https://github.com/browserless/chrome) is looking into this and should deploy a fix in a day or two.
I will keep you posted.

**Comment by sriv** [comment]
@GautierT - were you able to get anywhere with this? I'd like to put an example for this, and any help is welcome!

**Comment by saikrishna321** [comment]
@sriv I tested taiko with the latest Browserless container and it works.

1. Pulled the docker image
2. openBrowser({host:'localhost', port:'3000'}) Thats it ✅
