### ISSUE TITLE
taiko closing browser multiple times

### ISSUE THREAD

**Issue by Debashis9012** [getgauge/taiko#972]
### Expected behavior
The browser should close once.

### Actual behavior
The browser closes multiple times.

**Console output**
```
➜  Desktop taiko foo.js
 ✔ Browser opened
 ✔ Navigated to URL file:///Users/debas/Desktop/eleWrapper.html
[ { get: [Function: get],
    text: [AsyncFunction: text],
    description: 'Button with label Hello ' },
  { get: [Function: get],
    text: [AsyncFunction: text],
    description: 'Button with label Hello ' },
  { get: [Function: get],
    text: [AsyncFunction: text],
    description: 'Button with label Hello ' } ]
TypeError: Cannot read property 'result' of undefined
    at checkIfElementAtPointOrChild (/Users/debas/.nvm/versions/node/v10.15.3/lib/node_modules/taiko/lib/taiko.js:939:14)
TypeError: Cannot read property 'removeAllListeners' of null
    at _closeBrowser (/Users/debas/.nvm/versions/node/v10.15.3/lib/node_modules/taiko/lib/taiko.js:297:19)
{ Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
 ✔ Browser closed
 ✔ Browser closed
```

### Steps to reproduce
 run the below script 
```
const { openBrowser, goto, click ,closeBrowser } = require('taiko');
(async () => {
    try {
        await openBrowser();
        await goto("file:///Users/Desktop/eleWrapper.html");
        let a =  await button("Hello");
        let ele=  await a.elements();
        console.log(ele);
        click(ele[0]);
    } catch (error) {
        console.error(error);
    } finally {
        await closeBrowser();
    }
})();
```
**html snippet**
```
<!DOCTYPE html>
<html>
<body>

<h2>HTML Forms</h2>

<form action="/action_page.php">
  First name:<br>
  <input type="text" name="firstname" value="Mickey">
  <br>
  Last name:<br>
  <input type="text" name="lastname" value="Mouse">
  <br><br>
  <input type="submit" value="Submit">
   <input type="submit" value="Hello">


</form>

<form action="/action_page.php">
  First name:<br>
  <input type="text" name="firstname" value="Mickey">
  <br>
  Last name:<br>
  <input type="text" name="lastname" value="Mouse">
  <br><br>
  <input type="submit" value="Submit">
   <input type="submit" value="Hello">


</form>

<form action="/action_page.php">
  First name:<br>
  <input type="text" name="firstname" value="Mickey">
  <br>
  Last name:<br>
  <input type="text" name="lastname" value="Mouse">
  <br><br>
  <input type="submit" value="Submit">
   <input type="submit" value="Hello">
  

</form>
<p>If you click the "Submit" button, the form-data will be sent to a page called "/action_page.php".</p>

</body>
</html>

```

### Versions
```
Version: 1.0.3 (Chromium: 79.0.3945.16) 395170f7fcbebc20ee3e722389cefde023bd23e1
```

**Comment by negiDharmendra** [comment]
Works fine on master.

**Comment by Debashis9012** [comment]
I am able to reproduce this in master `b9cbccc6fdaedeee91b2adcd92c94c6c5f8ec600`.
Kindly find the below log:

```
{ Error: socket hang up
    at createHangUpError (_http_client.js:323:15)
    at Socket.socketOnEnd (_http_client.js:426:23)
    at Socket.emit (events.js:194:15)
    at endReadableNT (_stream_readable.js:1125:12)
    at process._tickCallback (internal/process/next_tick.js:63:19) code: 'ECONNRESET' }
TypeError: Cannot read property 'removeAllListeners' of null
    at _closeBrowser (/Users/debas/.nvm/versions/node/v10.15.3/lib/node_modules/taiko/lib/taiko.js:298:19)
    at process._tickCallback (internal/process/next_tick.js:68:7)
 ✔ Browser closed
 ✔ Browser closed
```

**Comment by Debashis9012** [comment]
The above script works with await, so closing this issue.
